### ISSUE TITLE
Can't delete client with API call

### ISSUE THREAD

**Issue by sochix** [toggl/toggl_api_docs#122]
Hello! 
I'm wrote a tests for my toggl wrapper, and found that after i delete client, in next request i got this clients in list, but with property **server_deleted_at**. How should I got all not deleted clients? 

P.s. it will be cool, if you add description of **server_deleted_at** to documentation.

**Comment by refiito** [comment]
server_deleted_at documentation will be added in near future.

Currently (for v8) you can get list of clients also with the /me?with_related_data query.
