### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by tompi** [toggl/toggl_api_docs#127]
Hi, i was toying with the idea of making an android widget with which you can start/stop a timer for a project, but would need the color of the project to make it recognizable from your excellent web ui.

Is there a way to get the "real" color(hex or similar) from the color "id" you supply?

**Comment by refiito** [comment]
Short answer is - no.

Long answer - there are a few upgrades planned to the Toggl webapp in regards to the project colour property and, with that, the hexadecimal values for colours will get added to the return.

However, as there is no fixed eta for that (it is in the shortlist, so we're not talking in years to come...), I won't give a date nor a approximation.
Just hang tight (leaving the issue open and will update as changes go live....)

**Comment by refiito** [comment]
Some and a bit late information - https://github.com/toggl/toggl_api_docs/blob/master/reports/summary.md#project-colors

**Comment by XavierNovella** [comment]
Hello,
Please note that I was checking the API for V2 and V8.
V8 only provides the color ID from 0 to 14.
V2 should supposedly provide the HEX value as per the explanation in documentation - However it seems not to be visible.
Can you please clarify?
Thanks!
