### ISSUE TITLE
Auth failure using curl example from API docs

### ISSUE THREAD

**Issue by bdcribbs** [toggl/toggl_api_docs#129]
I am having problems with authentication.  I boiled it down to the simplest possible case I can think of, which is copying and pasting the exact example `curl` command provided in the API documentation.  Of course, I replaced the API token with my own token.

Am I missing something obvious?

```curl -v -u REDACTED:api_token -X GET https://www.toggl.com/api/v8/me```

```
* Connected to www.toggl.com (23.253.20.253) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.toggl.com
*        start date: 2013-08-18 13:55:01 GMT
*        expire date: 2015-08-18 13:55:01 GMT
*        subjectAltName: www.toggl.com matched
*        issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certificates.godaddy.com/repository; CN=Go Daddy Secure Certification Authority; serialNumber=07969287
*        SSL certificate verify ok.
* Server auth using Basic with user 'REDACTED'
> GET /api/v8/me HTTP/1.1
> Authorization: Basic REDACTED
> User-Agent: curl/7.35.0
> Host: www.toggl.com
> Accept: */*
>
< HTTP/1.1 403 Forbidden
* Server nginx is not blacklisted
< Server: nginx
< Date: Sun, 22 Feb 2015 15:09:01 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Keep-Alive: timeout=20
< Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
< X-Toggl-Request-Id: a76525c0-df29-4e8e-7e15-bfd1504ef631
<
```

**Comment by chrisatomix** [comment]
I'm a bit concerned by the fact that your CURL installation is trying to use SSLv3, that should be completely disabled because it's insecure (See the POODLE bug from last year). Toggl doesn't even support SSLv3 anymore, it's disabled on their server.

Some more information that may help you:
https://disablessl3.com/

**Comment by refiito** [comment]
Most probably you're using the wrong token (use your personal token from your profile - https://www.toggl.com/app/profile)
You may be using the workspace token.

Also, the SSLv3... it's not enabled on our servers... 
With my, not the latest, curl version I was unable to get it to us SSLv3, could you please elaborate what curl version you have?

**Comment by bdcribbs** [comment]
Thanks, I was using the workspace token.

My curl version is:
```curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

This is what came from the OS package manager (Ubuntu 14.04.2, after an apt-get update + upgrade).  For what it's worth, the log messages still say "SSLv3, TLS handshake" even when I specify the `--tlsv1` option.

You've resolved my silly mistake, so I'll go ahead and close the ticket.  Feel free to follow up if you want more info regarding the SSL.  Thanks again.
