### ISSUE TITLE
Why is there 2 dates format on the same response ?

### ISSUE THREAD

**Issue by nicolas-besnard** [toggl/toggl_api_docs#132]
I just use the stop timer WS (`https://www.toggl.com/api/v8/time_entries/{entry-id}/stop`), and get the following response : 

```http
{
  "data" : {
    "start" : "2015-03-05T23:11:23+00:00",
    "stop" : "2015-03-05T23:11:25Z",
   "...": "..."
  }
}
````

As you can see, the `start` and `stop` doesn't use the same date protocol. Is that normal ?

**Comment by refiito** [comment]
Indeed it seems 'a bit' weird.
We'll have a look on the API side and force proper formats.
