### ISSUE TITLE
Problems with cURL call to API

### ISSUE THREAD

**Issue by simotho** [toggl/toggl_api_docs#133]
Hi,
I've some problems getting access to the API via. my cURL call.

Here is the code:

// create curl resource 
$ch = curl_init(); 

// set url 
curl_setopt($ch, CURLOPT_URL, $url); 
curl_setopt($curl, CURLOPT_USERPWD, "[token goes here]:api_token");
//return the transfer as a string 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
// $output contains the output string 
curl_setopt($ch, CURLOPT_HTTPHEADER, array(                                                                          
    'Content-Type: application/json'
));  
$output = curl_exec($ch); 

// close curl resource to free up system resources 
curl_close($ch); 

$json_result = json_decode($buffer, true);

echo '<pre>';
print_r($json_result);
echo '</pre>';

It just loads forever and nothing happens.
Any idea what is going on?

**Comment by refiito** [comment]
Do the requests from command line (using curl client) work? Or do they time out as well? (To rule out your connectivity issues).

Do all requests time out or a specific one?

**Comment by simotho** [comment]
I don’t get any result when trying in the terminal.

But I need it to work with PHP because I’m going to collect the informations automatic :-)

Den 18/03/2015 kl. 15.03 skrev Margus Mahler <notifications@github.com>:

**Comment by refiito** [comment]
Do all requests time out or a specific one?

Meaning - what is the endpoint?
Also - include -v flag for the command line utility.

```
curl -v ...
```

I've got the feeling that you're getting an unauthorised response.
Please check that your token is the one from your profile (https://www.toggl.com/app/profile).

**Comment by simotho** [comment]
It’s from the profile page the token is from :-)

Den 18/03/2015 kl. 16.53 skrev Margus Mahler <notifications@github.com>:

**Comment by refiito** [comment]
So, back to - what does the curl output (from command line) say? What is the request?

**Comment by simotho** [comment]
* Adding handle: conn: 0x7fdf4c80a600
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fdf4c80a600) send_pipe: 1, recv_pipe: 0
* About to connect() to www.toggl.com port 443 (#0)
*   Trying 23.253.62.116...
* Connected to www.toggl.com (23.253.62.116) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.toggl.com
* Server certificate: Go Daddy Secure Certification Authority
* Server certificate: Go Daddy Class 2 Certification Authority
* Server auth using Basic with user ’TOKEN'
> GET /api/v8/time_entries?start_date=01-01-2015&end_date=03-15-2015 HTTP/1.1
> Authorization: Basic N2ExNDQ2OTE2OTEwZmJhNmY3YWRhODgyNzMwYmZkNzc6YXBpX3Rva2Vu
> User-Agent: curl/7.30.0
> Host: www.toggl.com
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
* Server nginx is not blacklisted
< Server: nginx
< Date: Wed, 18 Mar 2015 16:05:44 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 19
< Connection: keep-alive
< Keep-Alive: timeout=20
< Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
< X-Toggl-Request-Id: c306c1ba-1137-4d72-4409-9ad7d83ee282
< 
Invalid start date

Den 18/03/2015 kl. 17.03 skrev Margus Mahler <notifications@github.com>:

**Comment by refiito** [comment]
As the response tells - start_date format (also, end_date format) is wrong.

From: https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range
```
start_date and end_date must be ISO 8601 date and time strings.
```
meaning: start_date should be smth in the lines of: 2013-03-10T15:42:46+02:00

Yes while, start_date, semantically, refers to a date and ISO 8601 is a timestamp format, for now no changes regarding naming/expected format are planned.
