### ISSUE TITLE
Toggle API doesn't specify Access-Control-Allow options

### ISSUE THREAD

**Issue by iamamused** [toggl/toggl_api_docs#136]
The report API specifies Access-Control headers allowing you to use jQuery Ajax requests to retrieve information. The Toggl API does not. Please update the Toggle API to include the same headers are the reports API. 

For example:

A request to the toggl API 

    curl -v -u TOKEN:api_token \
        -H "Content-Type: application/json" \
        -X GET https://www.toggl.com/api/v8/time_entries

Responds with:

    < HTTP/1.1 200 OK
    * Server nginx is not blacklisted
    < Server: nginx
    < Date: Tue, 24 Mar 2015 17:41:25 GMT
    < Content-Type: application/json; charset=utf-8
    < Content-Length: 14561
    < Connection: keep-alive
    < Keep-Alive: timeout=20
    < Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
    < X-Toggl-Request-Id: ba5a0ab9-2f06-48df-6e91-35a65d8d4ec0
    < Instance: togglbalancer4

Whereas the Reports API 

    curl -v -u TOKEN:api_token \
        -H "Content-Type: application/json" \
        -X GET "https://toggl.com/reports/api/v2/summary?user_agent=test&workspace_id=123"

returns similar headers but includes several *Access-Control* options:

    < HTTP/1.1 200 OK
    * Server nginx is not blacklisted
    < Server: nginx
    < Date: Tue, 24 Mar 2015 17:40:46 GMT
    < Content-Type: application/json
    < Content-Length: 10204
    < Connection: keep-alive
    < Keep-Alive: timeout=20
    < Expires: Tue, 24 Mar 2015 17:40:45 GMT
    < Cache-Control: no-cache
    < Access-Control-Allow-Methods: GET, OPTIONS
    < Access-Control-Allow-Headers: Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control, Authorization, Accept, Accept-Encoding, Accept-Language, Access-Control-Request-Headers, Access-Control-Request-Method, Connection, Host, Origin, User-Agent
    < Access-Control-Allow-Credentials: true
    < Instance: front3
    < Instance: togglbalancer4

Please add *Access-Control-Allow-Methods*, *Access-Control-Allow-Headers* and *Access-Control-Allow-Credentials* to the toggl API as well.

**Comment by refiito** [comment]
CORS options will be returned, for the main API, only for white listed domains, please contact support@toggl.com if you require white listing

https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md#cors

**Comment by iamamused** [comment]
ok thanks!
