### ISSUE TITLE
Retrieving workspace projects – possible to open up to non-admins?

### ISSUE THREAD

**Issue by t1mmen** [toggl/toggl_api_docs#137]
Hi,

I've built Toggl integration into my time, todo & activity tracking service [GotDone](https://www.gotdone.me). There is one thing that stuck me as very odd, and that is causing issues for my clients: [The list of projects can only be retrieved by admins](https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-projects), even though non-admins can see all existing, and create new projects,

Is there a way around this, or will you be willing to reconsider the current limitation?

Thanks!

**Comment by t1mmen** [comment]
Actually, it seems the documentation is incorrect: It is indeed possible for non-admin users to retrieve projects via the /workspaces/:wid/projects endpoint.

Can I trust this will continue to be allowed?

**Comment by chrisatomix** [comment]
As I understand it, this is controlled by the "Is Private" setting under each project ("Everybody in workspace can see this project. You can make it private.").

There's a Workspace-wide setting to allow non-admins to be able to create Projects, but they should be able to see all Workspace projects unless they're individually flagged as "Private".

I think the documentation needs to be clearer on this, but I don't see any reason why this behaviour would change (someone from Toggl should confirm this though).

GotDone is very slick, I especially love the GCal and Slack integrations! :)

**Comment by t1mmen** [comment]
That sounds very likely @chrisatomix, thanks. I must have overlooked the setting (it doesnt [appear to be on the 'edit project' screen](https://www.dropbox.com/s/lx0i85b9n1m5yxb/Screenshot%202015-04-02%2014.37.31.png?dl=0]))

I appreciate you checking out [GotDone](https://app.gotdone.me), and thank you for the kind words! Feel free to reach out if you have comments or suggestions :)

**Comment by chrisatomix** [comment]
It's actually on the "Team" tab at the bottom, I had to go looking for it too.

**Comment by webervin** [comment]
Alternative is to use https://github.com/toggl/toggl_api_docs/blob/master/chapters/users.md#get-current-user-data if user is non admin.
