### ISSUE TITLE
color ids - valid values

### ISSUE THREAD

**Issue by gaumeister** [toggl/toggl_api_docs#138]
Is there a list of valid values, rgb/hex values and names for the color ids used on projects? Either just a list or an API call that returns the valid values would be helpful. I'm working on some itDuzzit (cloud integration platform) connectors that make it easy to use the Toggl APIs, an having a nice valid-value list for the colors would be helpful.

**Comment by refiito** [comment]
current list in v8:
		"0":  "#4dc3ff",
		"1":  "#bc85e6",
		"2":  "#df7baa",
		"3":  "#f68d38",
		"4":  "#b27636",
		"5":  "#8ab734",
		"6":  "#14a88e",
		"7":  "#268bb5",
		"8":  "#6668b4",
		"9":  "#a4506c",
		"10": "#67412c",
		"11": "#3c6526",
		"12": "#094558",
		"13": "#bc2d07",
		"14": "#999999",

**Comment by XavierNovella** [comment]
Hello,
5 years in the future - Are this the current colors?
Thanks!
