### ISSUE TITLE
trying to get all tasks for a project doesn't work

### ISSUE THREAD

**Issue by joekrump** [toggl/toggl_api_docs#143]
I'm trying to get all tasks for a project using the path that is documented for getting all tasks belonging to a project. However, I only get back tasks that have {active: true}. I would like to get all tasks that belong to the project not just active ones and that is what I believe I am supposed to be able to do. Is this a bug?

**Comment by refiito** [comment]
append `active` as url parameter, valid options are `true/false/both`
eg. `https://www.toggl.com/api/v8/projects/{project_id}/tasks?active=both`
