### ISSUE TITLE
filter report: does not contain client_ids

### ISSUE THREAD

**Issue by matthiaswagnerwy** [toggl/toggl_api_docs#144]
hy,
is it somehow possible to retrieve report data from all clients except some specified? like you would use the ! in code...

i would like to use it to separate data from "real clients" and our own projects, where our company is listed as client as well.

thanks,
matt

**Comment by refiito** [comment]
While it's an interesting idea/suggestion I'm afraid there is nothing like that currently implemented.

I'll add it to our ideas box...

**Comment by matthiaswagnerwy** [comment]
thank you for the quick reply. if anyone else is interested, i guess an easy workaround will be to fetch all client id's, remove the ones that should not be included and build the query-string in a loop.
