### ISSUE TITLE
Add the ability to filter by field updated

### ISSUE THREAD

**Issue by intes** [toggl/toggl_api_docs#145]
In the list of requested parameters (https://github.com/toggl/toggl_api_docs/blob/master/reports.md) is not possible to use field updated. This is useful when you need to select the changes for a certain period. Now we have to get all the information to get only the changes. It loads your server and complicates the work for us.

**Comment by webervin** [comment]
Hello, this is something that we may consider in future, added it to our ideas bin. No promises though.

**Comment by chrisaligent** [comment]
See my update on #275 for a new workaround on this.
