### ISSUE TITLE
tag_ids filter not behaving

### ISSUE THREAD

**Issue by krazyjakee** [toggl/toggl_api_docs#146]
Here is my filter:
```
https://toggl.com/reports/api/v2/details?user_agent=x%40y&workspace_id=z&billable=both&tag_ids=0%2C459808%2C1182415&since=2014-06-03&order_desc=off&user_ids=123
```
Note the tag_ids...
```
tag_ids: "0,459808,1182415"
```

I would expect non-tagged tasks and tasks with those ids to be included, but it ignores the ids and just gets the non-tagged items. I simply want to perform the equivalent of a "tag_ids_not" to grab tasks that don't include a certain tag. Doesn't look like there is any way to achieve this.

**Comment by umrashrf** [comment]
See #159

**Comment by refiito** [comment]
Won't happen for reports/v2; added to suggestions/ideas for reports/v3
