### ISSUE TITLE
GOTCHA: Weekly Report uses UTC when no "since" param is passed.

### ISSUE THREAD

**Issue by lastobelus** [toggl/toggl_api_docs#147]
This means that if your time zone is set to something other than utc, and the same timezone on your api consumer, you should not get the current week by omitting since param.

To avoid confusion, and to avoid forcing developers to discover this by trial and error, I think it would be better if either the since param was required, or if the "since" that is used (whether passed **or** omitted) was echoed back in the response as a timestamp with timezone, so it is clear what the report represents

**Comment by webervin** [comment]
Reports api considers since and until in each user time zone  (based on currently  configured time zone of user). They are not UTC date's

**Comment by lastobelus** [comment]
"Reports api considers since and until in each user time zone"

I know this. The bug report was that if you *OMIT since (and until)* (ie, to get current week), UTC is apparently being used to calculate the week boundaries.

I haven't tested this recently since I lost interest in the tool I was building, but it was unambiguously true when I reported it.
