### ISSUE TITLE
Active workspace tasks query returns "null"

### ISSUE THREAD

**Issue by alexattws** [toggl/toggl_api_docs#150]
The following requests returns 200 OK and "null" as result.  This is clearly wrong because there are active tasks in the workspace.  Also, token owner is workspace admin.  Also, same thing happens for any setting for active.

curl -v -u ***redacted***:api_token -X GET https://www.toggl.com/api/v8/workspaces/42362/tasks?active=true

**Comment by Jacksonville** [comment]
I am having the same problem. The user is a pro user, please advise?

**Comment by refiito** [comment]
Closed due to old age
