### ISSUE TITLE
Allow Tagging of Time Entries across Workspace

### ISSUE THREAD

**Issue by gaumeister** [toggl/toggl_api_docs#157]
Currently the Toggl API only permits modification of a given User's time entries by their API. Even an administrative user cannot read or modify time entries. My suggestion is to __permit read and modify operations on time entries when using the API Key associated with a user that has administrative privileges__. 

My particular use case is that I would like to be able to use tagging across my user base to keep track of time entries that have been synced to other systems (accounting). Tagging is ideal for this use case, but only if it is enabled across all users. It is not feasible to enter API keys for each user.

**Comment by webervin** [comment]
Workspace administrator can edit time entries of other users. 
Use reports_api to get time entries that you need  to change, and then post them to time entries api using workspace administrator api key.

Feel free to play around with detailed report (and network inspector in your browser) in our web-app to get example of how it works.

**Comment by gaumeister** [comment]
Yes, this is what I'm doing (I use the reports_api and then try to use the time entries api PUT to tag time entries I need to modify). However, there must be something wrong with my account, then. For example, I am the admin and am using my API key. I have tried doing a GET request to the Toggl API with a time entry ID for another user, and I just get back {"data":null}. I try doing a PUT request to tag time entries, but that doesn't work either. Is there another URL convention I should be using? I'll file a help request with support on this but also wanted to let you know I'm still having an issue.

**Comment by webervin** [comment]
please double check that you follow [reports api doc] (https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md), you can not GET data from standard api, only reports api provides data of whole workspace. 

-> you may  write to support a toggl.com and provide curl examples on what are you doing, currently there is not enough information to say what is wrong.

**Comment by gaumeister** [comment]
@webervin thanks for your help. I got this resolved. My confusion was that the Toggl API does support cross user PUT requests (for example, to tag entries), but not the detailed Time Entry GET requests. The GET request was returning no data and it was fouling up my subsequent call to the PUT. Now, I'm using the Reports API to get all the data I need (thus replacing the Toggl API GET call), and using the Toggl API PUT call to do the modification.

Again thanks for the help.
