### ISSUE TITLE
Weekly report for whole month duration

### ISSUE THREAD

**Issue by Yankovsky** [toggl/toggl_api_docs#158]
I need to get data arranged in the same way as in weekly report but for whole month and without project subgrouping.
![Example](http://prntscr.com/8p7m9g)
Currently I have to options:
1) Make up to 6 weekly reports requests to get data for whole month;
2) Use detailed report and aggregate data by myself.
Am I missing something or is there no easier way to do it using toggl reports api?
Thank you.

**Comment by webervin** [comment]
weekly, as name implies is intended to be for one week only, we may consider some additional report types in future.
