### ISSUE TITLE
Add filter_tag_ids and/or print_tags input params to reports 

### ISSUE THREAD

**Issue by umrashrf** [toggl/toggl_api_docs#159]
I request time entries from summary report to process them and set a tag to separate those time entries which are processed. Is there a way to achieve that? 

I'd like that filter. Or allow [time_entries](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range) endpoint to filter based on tags, clients, projects etc.

Both works for me but former is convenient.

**Comment by joshatdf** [comment]
Would be great to get this implemented, as I also need this functionality to filter out specific tagged time entries.

**Comment by refiito** [comment]
Won't happen for reports/v2; added to suggestions/ideas for reports/v3
