### ISSUE TITLE
get total time logged

### ISSUE THREAD

**Issue by omnidan** [toggl/toggl_api_docs#162]
I want to get the total time logged for a certain workspace. Right now I'm doing the following:

```
{
  since: '1970-01-01'
}
```

Which results in this error:

```
{ [ReportError]
  code: 400,
  tip: 'Change your request and try again. Please refer to API documentation at https://github.com/toggl/toggl_api_docs if you need additional help' }
```

What would be the correct way to do this? Is it possible at all right now?

**Comment by refiito** [comment]
Firstly the since ought to be part of the HTTP request, also, an user-agent value needs to be provided and maximum timespan of a report is one year.

More at https://github.com/toggl/toggl_api_docs/blob/master/reports.md

**Comment by omnidan** [comment]
@refiito I do provide a user-agent header. I don't really understand why reports are limited to a year? Is there no way to get the total time logged for statistics?

**Comment by refiito** [comment]
For user agent, it's part of request parameter - https://github.com/toggl/toggl_api_docs/blob/master/reports.md#request-parameters

If you need an extended report, just make multiple calls and merge results

**Comment by omnidan** [comment]
@refiito Thank you for the notice. I am actually using [a library](https://github.com/7eggs/node-toggl-api) so it's probably sending the user agent the right way :)

Is there any reason for the restriction? There's no way to figure out how far back the history goes and stitching the total logged time together just seems like a huge hack/workaround.
