### ISSUE TITLE
Project duration is not including time entries [reporting api]

### ISSUE THREAD

**Issue by mrosendin** [toggl/toggl_api_docs#164]
I'm trying to get the duration of a project. I'm creating time entries and adding those entries to projects. When I get a project via the reporting API, the `duration` and `duration_without_task` are always `null`. I believe that the `duration` is properly set when I create and complete tasks, but not time entries. Would appreciate help if I'm doing something wrong.

Note: I want the response to return the project duration with seconds included and I'm not sure if it does that or not.

**Comment by refiito** [comment]
`duration` fields gives the total of time entries
`duration_without_task` gives the total of time entries that have no task attached

Did a bit of digging around and seems the the project you're asking data for has all the related time entries deleted... So the fields will indeed return NULL

**Comment by mrosendin** [comment]
Hey, thanks for the response--it helped. Now, can I retrieve all time entries in a project or would I have to use tasks for that? And if so, if the task is marked as 'complete', will its duration still be reflected in the total project duration, and will the completed task be in the tasks_page array?
