### ISSUE TITLE
Summary API will only return data for current year

### ISSUE THREAD

**Issue by PlaidShirtPat** [toggl/toggl_api_docs#168]
I am currently trying to pull all time entries since the beginning of last year. T
```
curl 
  -v -u $API_TOKEN:api_token \
  -H "Content-Type: application/json" \
  -X GET "https://toggl.com/reports/api/v2/summary?[...]&since=2015-1-1"
```
returns neither data nor an error message, but
```
curl 
  -v -u $API_TOKEN:api_token \
  -H "Content-Type: application/json" \
  -X GET "https://toggl.com/reports/api/v2/summary?[...]&since=2016-1-1"
```
will return everything from the current year. If there is a limitation based on year, it is not documented.

As a work around, adding until=2015-12-31 to the query will give you all entries from the previous year, however this forces you to use two queries where only one should be needed.
```
curl 
  -v -u $API_TOKEN:api_token \
  -H "Content-Type: application/json" \
  -X GET "https://toggl.com/reports/api/v2/summary?[...]&since=2015-1-1&until=2015-12-31"
```

**Comment by PlaidShirtPat** [comment]
Unfortunately the new documentation isn't correct. Queries return empty sets for calls that cross year boundaries.

**Comment by refiito** [comment]
please contact support@toggl.com with the full query you're doing (unable to reproduce on test data)
