### ISSUE TITLE
Until appears to mean "through" (Reports API v2)

### ISSUE THREAD

**Issue by webbj74** [toggl/toggl_api_docs#170]
When pulling reports and specifying "until" a date, my expectation would be that time entries after the until date are not included in summary or detail reports. In my experience summary and detail reports both include entries after the until date. For example if I get a detailed report **`until=2016-01-21`** I'm getting back entries which start after 2016-01-21. In practice it appears to me that the word "until" really means "through".

```
$ curl -s -u <redacted>:api_token -X GET "https://www.toggl.com/reports/api/v2/details?workspace_id=<redacted>&user_agent=webbj74&since=2016-01-14&until=2016-01-21&order_field=date&order_desc=on" > details-desc.json

$ php -r "print_r(json_decode(file_get_contents('details-desc.json'), true));" | grep '\[start\]' | head
                    [start] => 2016-01-21T19:06:27+01:00
                    [start] => 2016-01-21T18:59:25+13:00
                    [start] => 2016-01-21T18:29:12+10:00
                    [start] => 2016-01-21T18:27:14+10:00
                    [start] => 2016-01-21T18:26:10+10:00
                    [start] => 2016-01-21T18:06:38+10:00
                    [start] => 2016-01-21T17:59:04+10:00
                    [start] => 2016-01-21T17:55:59+10:00
                    [start] => 2016-01-21T17:53:18+00:00
                    [start] => 2016-01-21T17:45:53+10:00
```

Probably related to #149

**Comment by joeriharleman** [comment]
Hello @webbj74!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
