### ISSUE TITLE
Delete Project Users

### ISSUE THREAD

**Issue by GhostDZ9** [toggl/toggl_api_docs#173]
Hey Guys,

I am trying to do a REST api call to Delete Project Users. I followed the API and exactly what it says I have in my request and I get Error code 404 Not found. Please see attached screenshot and let me know what I am missing.
![screen shot 2016-01-29 at 3 28 59 pm](https://cloud.githubusercontent.com/assets/873459/12687315/0fad9224-c69d-11e5-8ba9-71e25d428c2c.png)

Thanks.

**Comment by madislohmus** [comment]
Hi GhostDZ9,

The api docs shortly mentions that the user must have access to delete. What this actually means is that the requester must be either the manager of the project or admin of the workspace the project is in. Can you confirm that this is the case in your request.

**Comment by GhostDZ9** [comment]
Hi,

The Authorization header includes the token from the admin on the account.

Regards,

GhostDZ9

**Comment by GhostDZ9** [comment]
Any ideas?

**Comment by refiito** [comment]
The request with the relevant X-Toggl-Request-ID had an authentication header that does not match the proper token/basic auth for that particular workspace admin/project user access combo.

Please check you have the correct **token** and the correct **project_user** ID

**Comment by GhostDZ9** [comment]
Could you show me what you see on your end? If I was passing in the wrong information to the server I wouldn't be getting a server response of 200 - OK.
