### ISSUE TITLE
Since parameter not honouring timestamp?

### ISSUE THREAD

**Issue by Subject22** [toggl/toggl_api_docs#177]
I want to get logs between specific date and time values. I have no issues getting logs between specific dates with the 'since' and 'until' parameters, but I can't seem to restrict the range with timestamps. Not sure if I'm just missing something or if the API just doesn't offer this functionality.

The following command gives me all logs for today, regardless of which time values I set, even if I choose a time since which no logs have been made (in my case nothing's been logged since 11am this morning). 

`curl -u xxxxxxxx:api_token 'https://toggl.com/reports/api/v2/summary?user_agent=xxxxxxx&workspace_id=xxxxxx&since=2016-02-23T11:00:00+13:00'
`

I've also tried encoding the special characters : and + with %3A and %2B respectively. Same result.

**Comment by seanculver** [comment]
I think that is a similar issue to https://github.com/toggl/toggl_api_docs/issues/149

Short answer is `since` and `until` are simple dates so time is ignored.

Here's a link to the docs https://github.com/toggl/toggl_api_docs/blob/master/reports.md#request-parameters
