### ISSUE TITLE
invalid character 'i' in literal true (expecting 'r') on time_entries/start

### ISSUE THREAD

**Issue by hpetev** [toggl/toggl_api_docs#178]
Everything looks fine when I do not provide any data to the api/v8 time_entries/start but once I add some data in the description field I get the following error

invalid character 'i' in literal true (expecting 'r')

**Comment by refiito** [comment]
Please check the data sent, error is reproduced by example with are request like:
```
curl -v -u "$TOGGL_TOKEN":api_token \
    -H "Content-Type: application/json" \
    -d '{"time_entry":{"duronly":ti, "created_with":"curl"}}' \
    -X POST https://www.toggl.com/api/v8/time_entries/start
```
note the "duronly" property having an invalid value...

**Comment by hpetev** [comment]
OK this is not what I am sending as data (PHP):
$data = ['time_entry' => ['description' => "$key", 'created_with' => 'curl']];
Also duronly is not specified in the API documentation. What does it stand for?

**Comment by WAftring** [comment]
Did you ever find a solution to this issue?

**Comment by hpetev** [comment]
No, I stopped using Toggl, short after I posted this issue.

**Comment by mguiney** [comment]
Just ran into this issue. Is there a known workaround/is a fix in progress?

**Comment by shedokan** [comment]
@mguiney Please reread the [previous comments](https://github.com/toggl/toggl_api_docs/issues/178#issuecomment-191933941), it's an issue with the JSON formatting.

You can use one of the many JSON validators online to pinpoint the issue with the JSON you're sending to our API.
