### ISSUE TITLE
Implement Shared Services in OSX?

### ISSUE THREAD

**Issue by grantkemp** [toggl/toggl_api_docs#180]
Hi 
do you know if the existing Toggl App has implemented shared services to interface with other OSX apps?  Would be great to use it with my app to speed up my workflow 
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/SysServices/introduction.html#//apple_ref/doc/uid/10000101i

**Comment by IndrekV** [comment]
This is a Desktop app specific request. Please create issue in the desktop app repo https://github.com/toggl/toggldesktop

Please add details about what workflow do you mean. What data would be shared.
