### ISSUE TITLE
Get list of users and its duration by task on project dashboard

### ISSUE THREAD

**Issue by concepta-thiago** [toggl/toggl_api_docs#184]
Hello there,

I trying to get the total hours by user for each tasks, i saw you guys have the 
https://github.com/toggl/toggl_api_docs/blob/master/reports/project.md
what works almost 100% for me, the only thing missing is the Total of Hours by user for each Task in that project. 

Today we can get the list of user and its total of hours that was worked per project, but is it possible to get the list of user and its duration for each tasks as well?

**Comment by dailos** [comment]
+1

**Comment by joeriharleman** [comment]
Hello @concepta-thiago!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
