### ISSUE TITLE
The filter with project_ids don't work

### ISSUE THREAD

**Issue by jairgarcia** [toggl/toggl_api_docs#185]
return $http.get( 'https://toggl.com/reports/api/v2/summary?workspace_id=1367142&user_agent=timjr&client_ids=' + clientId + '&project_ids=' + projectId );

The data is correct, but the response not filter by project ids.

I aprecciate any help, thanks.

**Comment by refiito** [comment]
Unable reproduce... you could contact support@toggl.com with the full query (incl. ID-s; excluding credentials)
