### ISSUE TITLE
Allow API rate limiter to be shared among all paid users belonging to a given workspace

### ISSUE THREAD

**Issue by SirLamer** [toggl/toggl_api_docs#186]
Your API documentation notes that the API rate limiter is implemented as a leaky bucket model per API key which plateaus at one query per second. In my application, I will have many users on many projects, but I am using one automated user with administrative rights to manage all projects, tasks, user membership on projects, etc. For a large application with many users for a given company, during a scheduled query of activity for the day, it's likely that the paginated results would take several separate queries to complete. If done with the one admin users to sample activity for all users, there is a reasonable risk of hitting the API limit and getting a failed HTTP response code, breaking the script. As a result and as a precaution against this, I am using the API key for each separate paid user to query their own timesheets so as to dodge the API limiter effect because it's unlikely that an individual user will have more than about 200 entries per month, however many users will have just a few or zero. The ultimate consequence of this is many more API queries per sync event are required because each user API key must execute the sync action separately, eliminating the opportunity for efficiency gained by doing it all at once with one master admin user account.

So... my point here is to suggest that the API limiter should be extended to n queries per second where n is the number of paid users belonging to a given workspace, and this limiter is shared among all users for the given workspace. Of course, no one is going to hit 30 queries per second or anything, but that means a large API request with many users and possibly a few thousand time entry records over several pages is not risking hitting the limit, which is fair since they would be paying for such access proportionately. The intent here would be to provide an incentive for application designers to consider their own computation efficiency interests, which would in turn benefit your own interests as well in that regard.

**Comment by refiito** [comment]
Interesting suggestion... making a note about this and recording for possible future plans...

Until something is planned/finite - I'd suggest you'll monitor the HTTP response and on 429 you'll have your script 'sleep' for a minute

**Comment by SirLamer** [comment]
Some platforms like Laravel don't make this easy, the most straightforward solution being to just include a "wait one second" instruction at the end of the method performing the API query. That seems really sloppy. I would like to tell Laravel "minimum one second between jobs being run on job queue named 'xyz'" but that is not available. So I suspect most users will just not do so.
