### ISSUE TITLE
User info access by manager account

### ISSUE THREAD

**Issue by Cambrone1** [toggl/toggl_api_docs#187]
Hi, I'm fairly recent to the toggl api and I haven't been able to figure out yet a way to access as the manager per se the time entries of the users working on a project the manager account supervises? I have been studying this for a while and can't seem to figure out how to access those data. 

Thank you,
David.

**Comment by refiito** [comment]
Maybe detailed report is the thing you're looking for?

https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md
