### ISSUE TITLE
Check if users are active

### ISSUE THREAD

**Issue by xDiglett** [toggl/toggl_api_docs#191]
I'm trying to check if workspace users are marked active, however I can't seem to get the required info.

I've tried **workspace_users**, which only returns one user and **/workspaces/$workspaceId/users** which doesn't show any information about active/inactive.

**Comment by refiito** [comment]
use the `GET https://www.toggl.com/api/v8/workspaces/{workspace_id}/workspace_users` endpoint, more at:
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspace_users.md#get-workspace-users
