### ISSUE TITLE
project tasks query returning null

### ISSUE THREAD

**Issue by zainengineer** [toggl/toggl_api_docs#194]
I tried to execute `https://www.toggl.com/api/v8/projects/{project_id}/tasks` but it is returning null.
I have assigned multiple tasks to the project but it is not working.

Is it available only in pro, or am I doing something wrong ?

curl -v -u {api_token}:api_token -X GET https://www.toggl.com/api/v8/projects/{project_id}/tasks

**Comment by webervin** [comment]
This feature is not available in free accounts, see https://support.toggl.com/why-go-pro/ for details
