### ISSUE TITLE
Allow Workspace-scope query of Project Users

### ISSUE THREAD

**Issue by SirLamer** [toggl/toggl_api_docs#198]
I'd like to be able to query "Get Workspace Project Users" which returns a collection of all project users, the purpose being to perform sanity check verification against local records. I don't see a way to do this, only on a per-project basis. This means I'd have to loop through an API query for every project separately, which is much less efficient than one large query.

**Comment by refiito** [comment]
Added to docs - https://github.com/toggl/toggl_api_docs/blob/master/chapters/project_users.md#get-list-of-project-users-in-a-workspace

**Comment by SirLamer** [comment]
Oh wow, thanks!
