### ISSUE TITLE
Suggestion: Allow multiple deletion of Clients

### ISSUE THREAD

**Issue by SirLamer** [toggl/toggl_api_docs#199]
Many models on Toggl allow deletion of multiple items with a comma-separated list, but Client does not. I tried to replicate the method documented for Projects, but it does not work for Clients.

There might be others which don't support multiple delete but I didn't test them all. Overall, the idea is that interaction with each data type in Toggl should be symmetrical to permit similarly patterned interaction with each.

**Comment by refiito** [comment]
This won't be implemented for API version 8.

Added to suggestions/ideas list for upcoming API version 9.
