### ISSUE TITLE
Client hrate & cur fields removed?

### ISSUE THREAD

**Issue by kanet77** [toggl/toggl_api_docs#201]
Do [clients](https://github.com/toggl/toggl_api_docs/blob/master/chapters/clients.md#clients) still have `hrate` and `cur` fields as noted in the documentation? I believe this was the case some time ago. Did the behavior change?

**Comment by refiito** [comment]
`hrate` and `cur` were removed from client (around 2014 with the major web client update), they were in the API return for some time for those who like to fetch it (historic reasons or something). Thanks for pointing out the obsolete info in the docs.
