### ISSUE TITLE
Support for simple task list

### ISSUE THREAD

**Issue by junajan** [toggl/toggl_api_docs#202]
Every day I create list of tasks for the next day/week which are later tracked using toggl.. It would be nice to have a possibility to create this list of tasks directly in toggl so I do not have to keep them somewhere else..

**Comment by joeriharleman** [comment]
Hello @junajan!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
