### ISSUE TITLE
Parameter consistency

### ISSUE THREAD

**Issue by cars10** [toggl/toggl_api_docs#204]
Why do we need so many different names for "start" and "end" times?
For example:
- The weekly report expects parameters named "since" and "until" as ISO 8601 (so just a date without time)
- The time entries endpoint expects "start_date" and "end_date" as RFC3339 (which includes time)
- The response from the time entries endpoint has "at", "start" and "stop" values (also as RFC3339)

I do get that the reports api and the toggl api are kinda seperated - but its still pretty annoying. I have to check the docs each time just to find out which word you chose for the specific task.

**Comment by joeriharleman** [comment]
Hello @cars10!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
