### ISSUE TITLE
Time entry duration inconsistent between Toggl API and Reports API

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl_api_docs#205]
"For time entries, the report API detailed time entry report returns a `dur` value that is in milliseconds. The regular API returns time entry durations as `duration` in seconds."

case: 360060

**Comment by webervin** [comment]
i suggest closing as wontfix. becasue both api v8 and reports api v2 are public documented stable apis that will not get any breaking changes in their lifespan. future public api versions will be announced separately.
