### ISSUE TITLE
error 404 when trying to get project users

### ISSUE THREAD

**Issue by mcmxc** [toggl/toggl_api_docs#208]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md#get-project-users

didn't work for me :( . It returns 404 error - page not found, although I'm passing the project id as a parameter. I can get project data by this id but cannot get project users :( Does anybody have the same issue?

**Comment by refiito** [comment]
You'll get a 404 on api/v8 if user has no access to the project - meaning, the project ID is wrong or the user making the request has no rights to see that particular project data (user isn't an admin, project is private and user isn't assigned to the project).

**Comment by mcmxc** [comment]
Sorry guys! In my case the problem was in node package I were using to access an API. Here it is: [node-toggl-api](https://github.com/7eggs/node-toggl-api). I fixed that error and send a PR there. If interested: this api wrapper were using wrong url address, which ends with `.../users`, not with `.../project_users` as it should.
