### ISSUE TITLE
Using API to get data from a Detailed Report I have saved

### ISSUE THREAD

**Issue by jessicam2** [toggl/toggl_api_docs#211]
I'm trying to use the API for our workspace to get data into an analytical tool, Qlik. I’m having problems figuring out which API to use. I’d like to use a detailed report I have saved (screenshot below). It’s year to date, so I’d just like to just pull this report / refresh the data via the API whenever we need it, 
When I enter the URL for this report in Qlik as well as in just browser it connects (as expected) but no data appear when I try to load data in Qlik. 
I’m guessing I need to enter “api” into this URL string somewhere, but I haven’t been able to figure that out yet.
Here's a screenshot of the type of report I just want to get via an API call so that I can generate custom graphs, pivot tables, etc.
ANY help is greatly appreciated! 

![image](https://cloud.githubusercontent.com/assets/21674623/20365227/33bffd52-ac14-11e6-8b95-3e15993a623c.png)

**Comment by jessicam2** [comment]
A follow-up note: 
When I looked at the dev code behind this report, I copied the request header and tried to re-use that and entered my user details when I try to use that in a web browser I receive the following error:
{"error":{"message":"api token missing","tip":"You can find your API Token in your profile at https://www.toggl.com","code":401}}

Here's the URL I'm using
https://www.toggl.com/reports/api/v2/details?rounding=Off&status=active&name=This+year%27s+detailed+report+for+our+team&billable=both&calculate=&sortDirection=asc&sortBy=date&page=1&grouping=&subgrouping=time_entries&order_field=date&order_desc=off&distinct_rates=Off&description=&since=2016-01-01&until=2016-12-31&period=thisYear&with_total_currencies=1&user_agent=myemail@test.com&workspace_id=12345&api_token=mypersonalapi12345&bars_count=31&subgrouping_ids=true&bookmark_token=ididnotchangethisfromwhatwasoriginallythere4&date_format=MM%2FDD%2FYYYY

Any thoughts?

**Comment by refiito** [comment]
You need to include the authentication header (HTTP Basic auth), just appending the token into the URL won't work.

More info at https://github.com/toggl/toggl_api_docs/blob/master/chapters/authentication.md

**Comment by jessicam2** [comment]
Hi,
Thanks for your quick response.
Unfortunately I’m still not clear on how that should work.
Here’s what I’m trying now based on what I understand in the link you sent:

https://www.toggl.com/reports/api/v2/details?rounding=Off&status=active&name=This+year%27s+detailed+report+for+our+team&billable=both&calculate=&sortDirection=asc&sortBy=date&page=1&grouping=&subgrouping=time_entries&order_field=date&order_desc=off&distinct_rates=Off&description=&since=2016-01-01&until=2016-12-31&period=thisYear&with_total_currencies=1&user_agent=myemail@test.org&12345myactualAPItoken123456:api_token&workspace_id=1507879&bars_count=31&subgrouping_ids=true&bookmark_token=1fea04363e8e23a04b0b161e941775d4&date_format=MM%2FDD%2FYYYY


but am still getting {"error":{"message":"api token missing","tip":"You can find your API Token in your profile at https://www.toggl.com","code":401}}
Thanks so much for your help!
Jessica

**Comment by webervin** [comment]
authentication header is not same as http uri parameter. please consult documentation of tools / frameworks that you are using on basic authentication or HTTP request headers.

**Comment by jessicam2** [comment]
Thanks - I removed the api from the uri parameter but kept everything else that I have in the above url.  
For the request header - does what i have in the screen below seem right? thanks so much!
![image](https://cloud.githubusercontent.com/assets/21674623/20406335/ef905132-acda-11e6-904f-8d85886936af.png)
![image](https://cloud.githubusercontent.com/assets/21674623/20406347/fdf1eb00-acda-11e6-97a9-933a2885df2a.png)

**Comment by meeDamian** [comment]
@jessicam2 taking one step back. Are `12345myactualAPItoken123456` or `123myapi456` the actual _tokens_ you're using or did you change it for the sake of privacy here?

If this is the actual token, you need to login to your Toggl account and take the token from the bottom of this page: https://www.toggl.com/app/profile . 

Also, make sure to keep it private afterwards.

**Comment by jessicam2** [comment]
Hi - sorry should have said that is a masked token for posting here. I am using my actual API token from my account profile page.

**Comment by refiito** [comment]
Header parameter needs to be authentication, please refer to the authentication link given - you must include a proper http basic auth header. Again please read the link given previously.

**Comment by jessicam2** [comment]
Thanks! I had read that wrong and thought the credentials were part of the header, but i changed my log in and IT WORKS! Thanks SO much for your help (clearly i'm technically inclined but not a programmer or in a technical role :)

**Comment by jessicam2** [comment]
One final (hopefully!) question. Can you explain how I can include the tag names in an API call? From what I can tell from the Tag table that __KEY_data is the Tag ID and @Value_u0 should be the value but when I get the data, I see values in the __KEY_data  field but I can't figure out how to find the actual name for the tags. 
Or do I need to actually specify the tag names in my request? 
Thanks again!
