### ISSUE TITLE
Grouped time entries in API

### ISSUE THREAD

**Issue by kkugelmann** [toggl/toggl_api_docs#212]
Hey there,

with the new API the functionality of continuing time entries is gone as far as i can see.
Is there a possibility to get time entries - grouped like on the dashboard - from the API or is it even planned to implement such a behaviour?

As I used the continuing time entries to get clean reports without much logic on the document generating side, it would be great to have a option to have a similar functionality.

All the best

**Comment by refiito** [comment]
grouping is currently only in the client side, there might be an option for detailed report in the future, but today and now (in API v8 and reports API v2), there's unfortunately no such option.

**Comment by blackjid** [comment]
hey @refiito can you comment on the logic to group time_entries together on the client side, this way we can implement the same logic on services consuming the api.

Thanks!
