### ISSUE TITLE
Stopping short entries may not work if they were created in a computer with the wrong system time

### ISSUE THREAD

**Issue by ntrrgc** [toggl/toggl_api_docs#213]
Hi.

I was just trying the API with a simple Python script. My intention was to have a global hotkey to stop Toggl tasks. This was the script:

```
#!/usr/bin/python3
import requests

api_token = "<my token>"

def get_current_entry_id():
    response = requests.get("https://www.toggl.com/api/v8/time_entries/current", auth=(api_token, "api_token"))
    if response.json()["data"] is None:
        return None
    else:
        return response.json()["data"]["id"]

def stop_current_entry():
    current_entry_id = get_current_entry_id()
    if current_entry_id is not None:
        response = requests.put("https://www.toggl.com/api/v8/time_entries/%s/stop" % current_entry_id, auth=(api_token, "api_token"))
        print(response.text)

stop_current_entry()
```

Amusingly, it only seemed to work sometimes, when the entries were a few minutes old... After inspecting the response of `/stop` (see the `print()` call) for a few executions I noticed something:

```
Restarting...
{"data":{"id":487442412,"wid":1361770,"billable":false,"start":"2016-11-24T11:42:57+00:00","stop":"2016-11-24T11:38:36+00:00","duration":-260,"description":"miau","duronly":false,"at":"2016-11-24T11:38:36+00:00","uid":2140805}}
Restarting...
{"data":{"id":487442412,"wid":1361770,"billable":false,"start":"2016-11-24T11:42:57+00:00","stop":"2016-11-24T11:39:14+00:00","duration":-222,"description":"miau","duronly":false,"at":"2016-11-24T11:39:14+00:00","uid":2140805}}
Restarting...
{"data":{"id":487442412,"wid":1361770,"billable":false,"start":"2016-11-24T11:42:57+00:00","stop":"2016-11-24T11:43:16+00:00","duration":19,"description":"miau","duronly":false,"at":"2016-11-24T11:43:16+00:00","uid":2140805}}
```

The `duration` property was negative in two of the three responses, and actually those correspond to the exact requests that did not really stop the entry.

I confirmed my suspicions later by looking at the `start` property and checking my computer clock drift with http://time.is/. Actually, the value of the `start` property was set by the web application when the entry was created by looking at the system clock, but calling `/stop` updates the `stop` property with the time from the server, resulting in a negative duration and therefore not stopping the entry!

This is not necessarily a bug of the API itself as the server can't possibly know the current time in the device that started the entry in order to compute the duration of the task, but it could be relieved by using time synchronization in the apps internally to ensure the uploaded time marks are precise, even if the computer clock isn't.

For my personal case, I fixed (workarounded?) it by enabling an NTP daemon in the computer I was using.

**Comment by joeriharleman** [comment]
Hello @ntrrgc!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
