### ISSUE TITLE
Reports API - Detailed report - project_ids not filtering

### ISSUE THREAD

**Issue by bolduz** [toggl/toggl_api_docs#215]
Hello everybody. I am getting a strange behaviour while trying to get the detailed report for a single client and a single project.

The `project_ids` parameter seems to not be working at all.
Below is a sample response to a request I made to `https://toggl.com/reports/api/v2/details` (with identifying informations edited out).

**MyClient** has four projects; each project has a different number of time entries.
The **workspace_id** is always the same, just like **MyClientID**.

```
+-------------------------------
|Client: MyClient
+-------------------------------

--> Project: My first project <--
Params: {'since': '2016-01-01', 'workspace_id': workspace_id, 'page': 1, 'user_agent': 'email@domain.com', 'client_ids': MyClientID, 'project_ids': FirstProjectID}
Requested page 1, got 39 results

--> Project: My second project <--
Params: {'since': '2016-01-01', 'workspace_id': workspace_id, 'page': 1, 'user_agent': 'email@domain.com', 'client_ids': MyClientID, 'project_ids': SecondProjectID}
Requested page 1, got 39 results

--> Project: My third project <--
Params: {'since': '2016-01-01', 'workspace_id': workspace_id, 'page': 1, 'user_agent': 'email@domain.com', 'client_ids': MyClientID, 'project_ids': ThirdProjectID}
Requested page 1, got 39 results

--> Project: My fourth project <--
Params: {'since': '2016-01-01', 'workspace_id': workspace_id, 'page': 1, 'user_agent': 'email@domain.com', 'client_ids': MyClientID, 'project_ids': FourthProjectID}
Requested page 1, got 39 results
```

You can see that each request returns the same amount of time entries (**39**), even if the `project_ids` parameter is changed.

The previous results were obtained with python and the `requests` module.
Below is the equivalent request made with `curl`:

```
curl -k -v -u {token_here}:api_token -X GET "https://toggl.com/reports/api/v2/details?workspace_id={workspace_id}&since=2016-01-01&user_agent=api_test&client_ids={client_id}&project_ids={project_id}"
```

Am I doing something wrong?

**Comment by webervin** [comment]
if you provide client_ids it means 'any projects of this client' and this condition is OR'ed with provided project_id's. remove `client_ids` from your request if you wish to filter only by project_ids instead.

**Comment by bolduz** [comment]
It works indeed, thank you.
May I suggest to add this explaination to the docs?
