### ISSUE TITLE
[Question] How to access the "PROJECT" values from the api?

### ISSUE THREAD

**Issue by wolass** [toggl/toggl_api_docs#219]
I did a reader from the API for R, but I can't seem to access the project descriptors from the JSON files. are these not included?

Here is the link to my function
https://github.com/wolass/togglR

**Comment by kanet77** [comment]
Projects are listed under workspaces: `GET https://www.toggl.com/api/v8/workspaces/{workspace_id}/projects` See [Get workspace projects](https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-projects).

You can also get a list of projects at the endpoint `https://www.toggl.com/api/v8/me?with_related_data=true`. See [Get current user data](https://github.com/toggl/toggl_api_docs/blob/master/chapters/users.md#get-current-user-data)

> By default the request responds with user properties. To get all the workspaces, clients, projects, tasks, time entries and tags which the user can see, add the parameter `with_related_data=true` If you want to retrieve objects which have changed after certain time, add `since` parameter to the query. The value should be a unix timestamp (e.g. `since=1362579886`)

Is this the information you're looking for?

**Comment by joeriharleman** [comment]
Hello @wolass!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
