### ISSUE TITLE
Century checking not accurate

### ISSUE THREAD

**Issue by sailingdeveloper** [toggl/toggl_api_docs#220]
Hi,

I am requesting any time entries since the beginning of this century (2000-01-01), but I get the error: `Date since=2000-01-01 is not in this century`. So I thought, maybe if I add a day, or a year, it will work. But even with 2005, I get the same error. `Date since=2005-01-01 is not in this century`.

I think you are mistakenly checking for > 10 years apart, because 2006 does work.

**Comment by refiito** [comment]
It's a bit misleading indeed, however the maximum span of any search is 1 year + as toggl started in 2006... there probably isn't any data in 2000 :)
