### ISSUE TITLE
Request time entries via api and include deleted entries?

### ISSUE THREAD

**Issue by kroeatschge** [toggl/toggl_api_docs#222]
hi there,
is there a paramter I can use to get also deleted entries using the time entries api or reports?

https://www.toggl.com/api/v8/time_entries

I get the information when geting the details for a single time entry. However I would like to be able the information "server_deleted_at":"2017-01-10T15:55:53+00:00" also in the detailed report. 

Is there a way to achive this?

thank you,
kro

**Comment by refiito** [comment]
Currently no, however will have something in the upcoming API versions

**Comment by aakay** [comment]
Hi @refiito , are there any time frame when we can expect this? I'm trying to access recently deleted entries but currently there's still no way to do it, it appears.

**Comment by refiito** [comment]
@aakay - I'm no longed employed at Toggl (for 2+ years now), please contact their support (probably via this https://toggl.com/track/contact/) with the question... I'm unsure if anybody follows closed issues on this repository these days.
