### ISSUE TITLE
How can I create time entries of other users as admin?

### ISSUE THREAD

**Issue by omerxx** [toggl/toggl_api_docs#225]
Hi,

Reading the [Time Entries docs](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md) I couldn't find any `user` parameter although @fonorobert in his last [change](https://github.com/toggl/toggl_api_docs/commit/f44c37d908108248246865283439c8f78e0e20ab), stated that:

> time entries in a workspace where the user is an admin are updated, retrieved and created

Is there such an option? 
It would be really helpful if so.
My use case (in case you were wondering) is a chatbot that helps users fill missing time entries in the past week... the bot is obviously using the manager's API key.

**Comment by omerxx** [comment]
@darrillaga @tanel @refiito - I would highly appreciate you guys input here... tagged you since you are the ones signed on the specific time entries doc page.
Thanks!

**Comment by refiito** [comment]
Current public API version (v8) does not allow time entries to be created for another user.

However, the currently in development API version (v9) allows it given the workspace the user is in is on a higher premium plan (please see https://support.toggl.com/why-go-pro/ - feature you're interested in is https://support.toggl.com/add-time-team/)

For v9 - basic structure is the same (route to POST the data is https://toggl.com/api/v9/workspaces/{workspace_id}/time_entries) and for adding time for another user, you just use the `user_id` field (having the proper value).

Something in the lines of:

payload:
```
{
  "start": "2016-11-02T07:08:27.984Z",
  "stop": null,
  "description": "Work Work",
  "pid": 345,
  "tid": null,
  "tags": null,
  "billable": true,
  "duration": -1478070507,
  "created_with": "Your Application Name Goes Here",
  "user_id": 123,
}
```

posted to:
`https://toggl.com/api/v9/workspace/{workspace_id}/time_entries`

Main differences with v8 - the payload and response aren't wrapped in "data" parameter

**Comment by omerxx** [comment]
@refiito Thank you for your help!
