### ISSUE TITLE
[Request] Adding/removing users in groups

### ISSUE THREAD

**Issue by kamil89** [toggl/toggl_api_docs#226]
Hello Toggl team,

does your api offer a way to add a user to group? Looking through existing endpoints I can see it is possible to add/update/remove groups, what about adding/removing users in a groups?

Would be nice to have such functionalities.

**Comment by donnysim** [comment]
It also makes it basically useless API, I can get groups, but I can't tell anything from it - what users are in the group, or what groups the user belongs to. I want to group times by group, but I just can't because I don't know which user is in which group :|

**Comment by pbassut** [comment]
yeah. I also wanted to know what users are in a given group

**Comment by pbassut** [comment]
Actually, that is possible with the GET `https://www.toggl.com/api/v8/workspaces/{WID}/workspace_users` endpoint. It tells you what users are in what group

**Comment by joeriharleman** [comment]
Hello @kamil89!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
