### ISSUE TITLE
How to get tag ID?

### ISSUE THREAD

**Issue by spleshka** [toggl/toggl_api_docs#232]
Hi guys,

We're writing Chrome extension for integration between Toggl and PM system. At the moment we stuck at the following issue: we're trying to get list of time entries by tags. [Reports API ](https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md) allows to do that, though we have to know tag ids. What we know from our end is only tag names. We haven't found anywhere an option to get tag IDs by tag names (at least nothing mentioned [here](https://github.com/toggl/toggl_api_docs/blob/master/chapters/tags.md)). 

Is there a way to get tag ID by tag name (preferrably bulk operation with a list of names) or, as a second way around, to get time entries by tag name?

Thanks in advance.

Cheers,
Ev.

**Comment by spleshka** [comment]
After a bit more searching I've found this API call: https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-tags. Looks like this is the only viable way to get list of tags for the workspace. 

Is there a chance that time entries (reports) could be fetched by tag names instead of tag ids?

**Comment by refiito** [comment]
We'd prefer using ID-s for matches whenever possible... so, no, no names
