### ISSUE TITLE
Stop the current timer without knowing ID

### ISSUE THREAD

**Issue by a-elliott** [toggl/toggl_api_docs#238]
I need to stop the current timer in one request. The only documented way to stop a timer in one request is to issue the time_entry_id in the URL. But what if we do not know the issue id?

**Comment by Clijsters** [comment]
+1  
As the API provides `GET https://www.toggl.com/api/v8/time_entries/current` to get the current timer and `PUT https://www.toggl.com/api/v8/time_entries/{time_entry_id}/stop` to stop a time entry with its id, I would intuitively use `PUT https://www.toggl.com/api/v8/time_entries/current/stop` to stop the current running timer but unfortunately this doesn't work. I see no reason not to support that way.

**Comment by refiito** [comment]
We'll probably have it in the next API versions...

**Comment by Sillium** [comment]
Any news on this? Would be very handy for my flic 2 Button, which can only trigger one request, not two consecutive requests with a passed variable.
