### ISSUE TITLE
Problem with API Authentication

### ISSUE THREAD

**Issue by acidcrash2005** [toggl/toggl_api_docs#248]
Hello!
I create new Extention fo After Effects with toggl button.

For this, I testing work with toggl API Authentication. My code is:

`<script>
        // Global Settings
        var appDetails = {
            togglAPIKey: '4e8dfc8f00469fd3e546c65e82e89a0e'
        };

        /**
         * Retrieves data from the Toggl API
         * @param {String} dataUrl (URL to retrieve)
         * @return {Object} data (Returned Data)
         */
        function retrieveTogglData(dataUrl) {
            // Create Base64 Encoded "Basic" Authorization string
            var authStr = 'Basic ' + window.btoa(window.appDetails.togglAPIKey + ':api_token');
            // Create Authorization header
            var requestHeaders = {
                'Authorization': authStr
            };
            
            
            // jQuery AJAX GET request, including Authorization headers
            jQuery.ajax({
                url: dataUrl,
                headers: requestHeaders,
                success: function(data) {
                    // Successful GET request
                    // Return the data
                    console.log(data);
                    return data;
                }
            }).fail(function(errorData) { // Failure to retrieve data// Show error alert
                alert('Error retrieving data from the Toggl API!' + "\r\n" + 'Error Code:' + errorData.statusText); // Return false
                return false;
            });
        }

        jQuery(document).ready(function(){
        // Retrieve 'weekly' default report
         var weeklyData = retrieveTogglData('https://www.toggl.com/api/v8/me');
        });
    </script>`

But my browser gives me the error:
http://joxi.ru/EA4Kpd9Ie4OV2b

`XMLHttpRequest cannot load https://www.toggl.com/api/v8/me. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://toggle.local' is therefore not allowed access.`

Please Help me! I get no idea what is wrong!

**Comment by refiito** [comment]
Your snippet violates the same-origin-policy, see more at https://en.wikipedia.org/wiki/Same-origin_policy

At this time we're temporarily not allowing CORS whitelisting (authentication will get an overhaul in the next API versions)

**Comment by derkjn** [comment]
Any idea on when CORS will be re-enabled?

**Comment by refiito** [comment]
CORS is enabled, contact support@toggl.com for whitelisting.
