### ISSUE TITLE
Dev or Test Instance

### ISSUE THREAD

**Issue by mitchstewart** [toggl/toggl_api_docs#258]
I'm looking to develop some custom functionality for consolidating Toggl tasks. Since Toggl tasks are not available in the Free edition, I have to use our production environment for testing, which is less than ideal. Would toggl give out a developer/QA/Test/Dev instance to a paying customer? If not, do you have a recommendation for development that does not put production time entries at risk?

**Comment by joeriharleman** [comment]
Hello @mitchstewart!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
