### ISSUE TITLE
How can i get the tid from time entry details endpoint?

### ISSUE THREAD

**Issue by bauklotz** [toggl/toggl_api_docs#270]
I have a problem to get the tid from the time entry details endpoint.

I looked into the documentation and in the example for [Time Entries](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md) and there is a property list with **tid: task ID (integer, not required)**

Is the tid gone in V8 of the API or is this a bug?

**Comment by shedokan** [comment]
The task ID is still in `tid` in V8, but if you are on a free workspace you won't see it or be able to use it.

If you are on a paid workspace, and are still having issues please contact support@toggl.com with the specific details of your workspace.
