### ISSUE TITLE
Open API (Swagger) API documentation

### ISSUE THREAD

**Issue by mxr576** [toggl/toggl_api_docs#273]
Hey,

I'm wondering whether you are working on an Open API (or any other industry standard API) documentation for your APIs to extend/replace these Markdown files? Do you already have something to share? 
I think it would be helpful to have something like this. For example, it could be used to auto-generate SDK-s for your APIs. 

Regards, Dezső.

**Comment by refiito** [comment]
Hi,

Not for the v8 and reports v2 versions. Might consider for upcoming versions.

**Comment by mxr576** [comment]
Do you have any estimate when the new APIs are going to be realised? Does it worth to create an SDK for the current APIs or they are going to be deprecated soon?

**Comment by refiito** [comment]
API versions v9 and reports v3 are being actively developed currently and the documentation will be released as Toggl's clients have been migrated.

As of now there's no roadmap nor deadlines...

**Comment by justinr1234** [comment]
@refiito was there ever a swagger API generated? Would be incredibly useful for: https://datafire.io
