### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by bernhof** [toggl/toggl_api_docs#274]
I'm evaluating Toggl on a free account and have created 50+ projects in my workspace. When I try to list them all [as documented here](https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-projects), I only get the first 47. How do I get the next "page" or set of projects? I'm guessing this applies to clients, time entries etc. as well.

Toggl looks promising in general, but It's critical for us to be able to periodically sync up with our own internal systems and for this purpose we need to be able to list *all* projects in the workspace.

As far as I can tell, there is no documented pagination support in the v8 API. How do I proceed here?

Thanks

**Comment by zimmerel** [comment]
There is no need for pagination on a projects request using the v8 API. I use the standard get request every day to get the data for hundreds of products without using pagination.
GET https://www.toggl.com/api/v8/workspaces/{workspace_id}/projects

It appears to me that you might have some filters on or possibly that you only have 47 projects. By default, the request only returns active projects unless you specify it to do both. As far as I know, you only need pagination when using the v2 API to pull reports, which is limited at 50 records per request.

**Comment by bernhof** [comment]
You're right - I had missed the part about the default filter being active projects only. `GET /workspaces/{workspace_id}/projects?active=both` returned all projects in our workspace. Thanks for the hint! :)
