### ISSUE TITLE
TogglAPI.Net - TimeEntryService.List - Cannot deserialize JSON array into type 'Toggl.ApiResponse'. 

### ISSUE THREAD

**Issue by ghost** [toggl/toggl_api_docs#276]
Toggl Reports API v2

In code below (vb code file attached), an unhandled exception **Cannot deserialize JSON array into type 'Toggl.ApiResponse'.** is thrown on the line **For Each objTE In objTimeEntrySrv.List(objTEParams)**

Cannot understand why this error is thrown - please advise.

`Sub Main()
        Dim objReportService As New Toggl.Services.ReportService(APIKEY)
        Dim objReportParams As New Toggl.QueryObjects.DetailedReportParams
        Dim result As DetailedReport
        
        Dim objTimeEntrySrv As New Toggl.Services.TimeEntryService

        With objReportParams
            .Since = DateTime.Now.AddYears(-1).ToIsoDateStr
            .Until = DateTime.Now.AddMonths(-6).ToIsoDateStr
            .Billable = "0"
            .UserAgent = "TogglAPI.Net"
            .WorkspaceId = "390167"
        End With
        result = objReportService.FullDetailedReport(objReportParams)

        Console.WriteLine("Count: " & result.Data.Count)

        objTimeEntrySrv = New Toggl.Services.TimeEntryService(APIKEY)

        For Each objRte As ReportTimeEntry In result.Data

            'output report time entry details
            Console.WriteLine("ID: " & objRte.Id)
            Console.WriteLine("Client: " & objRte.ClientName)
            Console.WriteLine("Project: " & objRte.ProjectName)
            Console.WriteLine("User: " & objRte.UserName)
            Console.WriteLine("Task name: " & objRte.TaskName)
            Console.WriteLine("Billable: " & objRte.Billable)
            Console.WriteLine("IsBillable: " & objRte.IsBillable)
            Console.WriteLine("Duration: " & objRte.Duration)
            Console.WriteLine("Start: " & objRte.Start)
            Console.WriteLine("Stop: " & objRte.Stop)
            Console.WriteLine("Updated: " & objRte.Updated)
            Console.WriteLine("[Time entries]")

            'get project time entries
            If Not IsNothing(objRte.ProjectId) Then
                Try
                    Dim objTEParams As New TimeEntryParams
                    objTEParams.ProjectId = objRte.ProjectId

                    For Each objTE In objTimeEntrySrv.List(objTEParams)
                        Console.WriteLine("Description: " & objTE.Description)
                        Console.WriteLine("Duration: " & objTE.Duration)
                        Console.WriteLine("Tag names: " & String.Join(", ", objTE.TagNames.ToList))
                    Next
                Catch ex As Exception
                    Console.WriteLine("Error: " & ex.Message)
                End Try

            End If
            Console.WriteLine("-----------------------------------")
            Console.ReadKey()
        Next

        Console.ReadKey()
    End Sub`
[Module1.txt](https://github.com/toggl/toggl_api_docs/files/1284640/Module1.txt)

**Comment by joeriharleman** [comment]
Hello @ghost!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
