### ISSUE TITLE
Cannot get deactivated user's time entries

### ISSUE THREAD

**Issue by bluefeet32** [toggl/toggl_api_docs#278]
I have a python script pulling time entry data from Toggl in order to do my own local processing on it.

This works fine for users who are active, but I cannot GET time entries for user accounts that have been deactivated. I'm trying to pull time entries from a specified date range using:
GET https://www.toggl.com/api/v8/time_entries?start_date={}&end_date={}
and just get a blank request as a return value.
Even specifying the exact time entry I want data for (GET https://www.toggl.com/api/v8/time_entries/{time_entry_id}) returns {"data":null}

On the online interface it is possible to generate reports with these deactivated users included so I was wondering if this should be possible with the API?

**Comment by refiito** [comment]
Check the detailed report - https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md

An inactive user cannot access his/her time entries, so only a workspace admin can do that (by fetching a report) as the time entries belong to the workspace, not user.

**Comment by webervin** [comment]
only reporting api (using workspace administrator api token) can access time entries of deactivated  user. deactivated user himself is treated as having no access to workspace.
