### ISSUE TITLE
Is is possible to put the workspace_id in a visible location?

### ISSUE THREAD

**Issue by YishTish** [toggl/toggl_api_docs#279]
Scenario: An invoicing app would like to integrate with Toggl to generate bills based on the reports imported from Toggl.
Problem: App user needs to provide the workspace_id in order to receive reports. The workspace_id is only visible in the URL query string.
Request: would it be possible to have the workspace_id visible to the non-technical user, so that we can guide them to go and paste it in our app?

Thanks!

**Comment by shedokan** [comment]
In order to authenticate you'll need the user's api token(which you can get in "My Profile"), please see these docs on how to authenticate and get a list of user's workspaces:
https://github.com/toggl/toggl_api_docs/blob/master/chapters/authentication.md#http-basic-auth-with-api-token
