### ISSUE TITLE
Lack of OAuth authentication

### ISSUE THREAD

**Issue by seandmatthews** [toggl/toggl_api_docs#280]
It's 2017 and you guys don't have oauth based authentication on your API.
Who needs scoped access to user data anyway?
All my users should just give me their toggl username and password, and trust me not to do anything nefarious with it.

**Comment by adeperio** [comment]
Hi Just following on from this comment. Are there any plans to offer OAuth at the moment on the Toggl API?

**Comment by carloliwanag13** [comment]
Would also love to hear about any plans for this. Thanks!

**Comment by Laskewitz** [comment]
Wow - this issue has been open for a while. Any updates for this? @gilberthdez

**Comment by joeriharleman** [comment]
Hello @seandmatthews!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
