### ISSUE TITLE
Possible problem with instructions for session cookie authentication

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl_api_docs#283]
A user mentioned that the example provided in the docs isn't working
https://github.com/toggl/toggl_api_docs/blob/master/chapters/authentication.md#authentication-with-a-session-cookie

This doesn't work
curl -v -u xxxxxxxxxxxxxxxxxx:api_token -X POST
https://www.toggl.com/api/v8/sessions

This does work
curl -d -v -u xxxxxxxxxxxxxxxxxx:api_token -X POST
https://www.toggl.com/api/v8/sessions

They are getting `Error 411 (Lenght Required)`. 

---
Case 562017

**Comment by webervin** [comment]
because HTTP spec says that method POST must include body, refer to curl manual on how to provide body.
