### ISSUE TITLE
Unable to connect to any report besides time_entries

### ISSUE THREAD

**Issue by tomo-111** [toggl/toggl_api_docs#286]
Hello,
I'm trying to connect to toggle API through R (utilizing httr package).

While I'm able to connect (and get data) when this url is used:
```
library(httr)
url<- 'https://www.toggl.com/api/v8/time_entries'
t<-GET(url, authenticate('myAPItoken', 'api_token'),add_headers('User-Agent'= 'tomo_111@yahoo.com' ), verbose())
```

and get this feedback (and data):
```
> GET /api/v8/time_entries HTTP/1.1
-> Host: www.toggl.com
-> Authorization: Basic longcodedstring
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> User-Agent: tomo_111@yahoo.com
-> 
<- HTTP/1.1 200 OK
```
so I assume my authentification/usage of httr R package is +- correct

when changing the URL to this for instance and utilize the same command I get:
```
url<-'https://toggl.com/reports/api/v2/weekly'
t<-GET(url, authenticate('myAPItoken', 'api_token'),add_headers('User-Agent'= 'tomo_111@yahoo.com' ), verbose())

 GET /reports/api/v2/weekly HTTP/1.1
-> Host: toggl.com
-> Authorization: Basic MDdkZjE2ZDc0NTdmMzRhODVjZmYzN2NlMWZiMjQ1OGI6YXBpX3Rva2Vu
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> User-Agent: tomo_111@yahoo.com
-> 
<- HTTP/1.1 400 Bad Request
```

but more interestingly the content of the message points me to 'no user agent', althought it was provided?
```
str(content(t))
List of 1
 $ error:List of 3
  ..$ message: chr "Required parameter 'user_agent' is missing from request. You should specify the name of your application or you"| __truncated__
  ..$ tip    : chr "Change your request and try again. Please refer to API documentation at https://github.com/toggl/toggl_api_docs"| __truncated__
  ..$ code   : int 400
```

Please note I'm aware workspace ID is also required, but since I was able to make this work in Python it appeared there is a message if that is missing and adding it doesn't seem to help in this case.

Thanks for any suggestions.

**Comment by refiito** [comment]
Hi,

API v8 isn't the reports... For time entries please use the detailed report https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md

However you have to include the user_agent as part of the query string, not just header for the reports v2.
