### ISSUE TITLE
[Request] external_id support

### ISSUE THREAD

**Issue by robertbounds** [toggl/toggl_api_docs#291]
Hi,

I like Toggl a lot, and am finding I would like to marry it up with my employer's PSA software, NetSuite (Oracle) OpenAir.

While I can create "my projects" from OpenAir in Toggl, what I would like to do is integrate my project-customer time entries from Toggl automatically with my OpenAir timesheet for the employer's billing process.  I'm sure I could find a way to do that if I could add a quality like an *external_id* when creating / updating Toggl projects, and customers.  The goal would be a relationship like "OpenAir internal_id = Toggl external_id". (That could be a great way to open up clean, time-tracking integrations with salesforce by, say, account and opportunity IDs, too!)

If this is already available, I missed the documentation reference.  Otherwise, please take this "issue" as a feature request to add on top of a fantastic product :)

Thanks!
Rob

**Comment by webervin** [comment]
> The goal would be a relationship like "OpenAir internal_id = Toggl external_id". 
you just need to store such relationship in your local database and use that map in your application.
