### ISSUE TITLE
Clarify confusing timezone description in README.md

### ISSUE THREAD

**Issue by parasti** [toggl/toggl_api_docs#292]
From the README:

> Please do note that the times and dates are stored in UTC (GMT), on return the data is set into the appropriate timezone according to the setting in user profile.

After reading that, I still have no idea what timezone is used in the request/response. If it is in UTC, the second part of that sentence is unnecessary. If it's not in UTC, the first part of that sentence is unnecessary.

**Comment by joeriharleman** [comment]
Hello @parasti!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
