### ISSUE TITLE
Tasks: Add GET Tasks to docs

### ISSUE THREAD

**Issue by comfytoday** [toggl/toggl_api_docs#293]
The GET all tasks request is not included in the docs:

GET /api/v8/workspaces/{WID}/tasks

Which leads me to ask: Is it possible to send a query to filter based on updated date, etc?

**Comment by alexey-pelykh** [comment]
[This](https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-tasks) doesn't fit as docs?

**Comment by comfytoday** [comment]
Damn, thanks.

I was looking here:
https://github.com/toggl/toggl_api_docs/blob/master/chapters/tasks.md
