### ISSUE TITLE
Time entry queries no longer accepting min and max values for start_date and end_date

### ISSUE THREAD

**Issue by Calseon** [toggl/toggl_api_docs#294]
I'm using TogglAPI.NET in my C# application. Everything was working fine up until yesterday when querying time entries would sometimes fail. 

I found out that whenever it failed it was sending the following request:
https://www.toggl.com/api/v8/time_entries?start_date=0001-01-01T00:00:00-05:00&end_date=9999-12-31T23:59:59-05:00
I would get an error 400 Bad Request, with the description "Invalid start date". If I change the starting year from 0001 to 2017, then the start date would pass but then it would say "Invalid end date".

A request like this would work fine:
https://www.toggl.com/api/v8/time_entries?start_date=2010-11-11T00:00:00-05:00&end_date=2017-12-31T23:59:59-05:00

Has the API changed recently such that drastically extreme start and end dates are no longer accepted?

**Comment by refiito** [comment]
No changes to said endpoint done.

If you're using 0001 as the year then it's outside of the supported range. For fetching time entries for longer period than 3 months use the reporting API, see here - https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md

Also as a hint - the body of the response mostly contains some human-readable message about what went wrong...
