### ISSUE TITLE
time_entry can't be blank

### ISSUE THREAD

**Issue by kjsb25** [toggl/toggl_api_docs#299]
I'm having an issue with starting a time entry.

I copy the code in exactly from  toggl_api_docs/chapters/time_entries.md , and only edit my api token and the pid (to align it with one of my own projects), and get an error stating the time_entry can't be blank. Shown below.

![image](https://user-images.githubusercontent.com/6875053/36647410-e3a8d536-1a4a-11e8-86c5-101f8253376c.png)

Any tips on what I'm doing wrong? The documentation seems to be in need of an update, because I don't see how editing two values would make it not well formed JSON.

**Comment by kjsb25** [comment]
Issue staled.

**Comment by fischgeek** [comment]
What was the resolution on this? I'm getting the same error.

**Comment by kjsb25** [comment]
Unfortunately I went to testing with something other than curl, and didn't have the same error as I did here. My guess was the json formatting was malformed somehow but I couldn't nail down the issue. Sorry :/
