### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by IgorGee** [toggl/toggl_api_docs#304]
Hi there.

I saw #11, and I was wondering if that conclusion was still relevant today.

If it is, does that mean I need to ask my users, who signed up via google, to grab their api tokens for me?

**Comment by tdresser** [comment]
The open source app does this [here](https://github.com/toggl/mobileapp/blob/2050ec075008e3edfdd1c462b51796acd8932cf9/Toggl.Networking/Network/Credentials.cs#L39), but I think we'd need the client id used by the toggl backend to use this technique.

I'm not positive though.

**Comment by joeriharleman** [comment]
Hello @IgorGee!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
