### ISSUE TITLE
Error calling Toggl report API

### ISSUE THREAD

**Issue by jeevaeastpoint** [toggl/toggl_api_docs#305]
I have been trying to use the Toggl's report API and hit with a problem. Calling a weekly report endpoint by passing the required headers. One of the header is "user_agent", even though this header is added to the request and sent, I keep getting an error "Required parameter 'user_agent' is missing from request. You should specify the name of your application or your email address so we can get in touch with you in case you're doing something wrong." Any idea why this is happening. I have tried the same from postman but result is the same. 

Curl output below 

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying xx.xxx.xx.xx...
* TCP_NODELAY set
* Connected to toggl.com (xx.xxx.xx.xx) port xxx (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ******************************
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=EE; postalCode=10143; ST=Harju; L=Tallinn; street=Ravala 8; O=Toggl; OU=PremiumSSL Wildcard; CN=*.toggl.com
*  start date: Sep 11 00:00:00 2017 GMT
*  expire date: Oct 25 23:59:59 2018 GMT
*  subjectAltName: host "toggl.com" matched cert's "toggl.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
* Using Stream ID: 1 (easy handle 0x7f9068805800)
> GET /reports/api/v2/weekly/ HTTP/2
> Host: toggl.com
> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> User-Agent: curl/7.54.0
> Accept: */*
> user_agent: <my email address>
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 400 
< server: nginx
< date: Fri, 30 Mar 2018 23:03:02 GMT
< content-type: application/json
< content-length: 379
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control, Authorization, Accept, Accept-Encoding, Accept-Language, Access-Control-Request-Headers, Access-Control-Request-Method, Connection, Host, Origin, User-Agent
< access-control-allow-credentials: true
< instance: reports2
< instance: web3
< strict-transport-security: max-age=15552000; includeSubDomains
< x-content-type-options: nosniff
< x-we-are-hiring: https://jobs.toggl.com/
< x-request-id: 40f722c7c4f1294c9ff9ed92095347d5
< via: 1.1 google
< set-cookie: GCLB=CK_CmqX85dijFg; path=/; HttpOnly
< alt-svc: clear
< 
* Connection #0 to host toggl.com left intact
{"error":{"message":"Required parameter 'user_agent' is missing from request. You should specify the name of your application or your email address so we can get in touch with you in case you're doing something wrong.","tip":"Change your request and try again. Please refer to API documentation at https://github.com/toggl/toggl_api_docs if you need additional help","code":400}}-

**Comment by webervin** [comment]
Your request is indeed missing value for user_agent, as is written in response. 
It is not header, and should be specified as GET query parameter: `?user_agent=way_to_contact@developer-of-api.client`, blank value is not accepted.
`workspace_id` is also obligatory. and probably you want to specify value for `since` for weekly report as well.

See https://github.com/toggl/toggl_api_docs/blob/master/reports.md#request-parameters for more information.
