### ISSUE TITLE
In the Detailed Report, the ReportTimeEntry Ids cannot be used with the TimeEntries call

### ISSUE THREAD

**Issue by davidnmbond** [toggl/toggl_api_docs#306]
The Detailed Report API call:
https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md
...returns a list of ReportTimeEntries with Ids that cannot be used to call the Time Entry call:
https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md

Please include the Time Entry Id into the ReportTimeEntry response to remedy this.

**Comment by danielabbatt** [comment]
What operation are you trying to do for the time entry?
I can get a list of entries in the report each of which has an "id" under the "data" node.
For each of those I perform a get on https://www.toggl.com/api/v8/time_entries/nnnnnnn and it works fine, the details for the time entry are returned.

**Comment by danielabbatt** [comment]
On closer investigation it seems that the url will only work for your own time entries and does not allow you to access time entries belonging to other users in the same workspace, even if you get read those time entries and get their Ids as part of a detailed report!

**Comment by webervin** [comment]
please be more specific what you want to do.

- [reports api](https://github.com/toggl/toggl_api_docs/blob/master/reports.md) does return time entries of other users if [rights](https://support.toggl.com/user-access-rights/) allow that for requester.
- to be able [add time](https://support.toggl.com/add-time-team/) for other people, you need corresponding [plan](https://support.toggl.com/category/pricing-plans/) and be administrator of workspace.

**Comment by davidnmbond** [comment]
Not looking to add time - just to retrieve a single TimeEntry.  It is possible for the (admin) user to retrieve en masse with a Detailed Report, so why would it not be possible to retrieve the individual entry.  The PUT verb works fine, so why would it not be possible to do a GET?  Clearly a bug, I'm afraid.

**Comment by webervin** [comment]
fetching of time entries for other  people is among tasks of reports api, not api v8. so no bug here.

**Comment by jalovatt** [comment]
> fetching of time entries for other people is among tasks of reports api, not api v8. so no bug here.
> 
> refer to `time_entry_ids: A list of time entry IDs separated by a comma` parameter in documentation.

Necrobump, but I just ran headfirst into the same issue. For what it's worth, the first paragraph of `time_entries.md` says that we can get both our own entries and any entries for workspaces where we're an admin:
```
Only his/her time entries and time entries in a workspace where the user is an admin are updated, retrieved and created.
```
