### ISSUE TITLE
How to generate detailed report for all team members?

### ISSUE THREAD

**Issue by v0l0d** [toggl/toggl_api_docs#309]
Hello,

I'm generating detailed report based on https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md
but it does it only for current user (I'm not setting 'users' parameter at all)

I was going to get all workspace users and use these at 'users' field, but having 2 active and 3 inactive users I receive 46+ entries

Can you help me please build detailed report for all users?

Thank you
Vladimir

**Comment by refiito** [comment]
Hi,

Include the user ID-s (not to be confused with workspace user ID-s) to the `user_ids` parameter, the ID-s should be separated by comma.

More on shared params for all reports - https://github.com/toggl/toggl_api_docs/blob/master/reports.md#request-parameters

**Comment by v0l0d** [comment]
sorry, my bad: wrong date range
