### ISSUE TITLE
Group assignment to project function missing

### ISSUE THREAD

**Issue by Dakror** [toggl/toggl_api_docs#312]
Hello,
we're trying to create projects via the API and assign our default user group to the project, just like in the Webapp. But there is currently no API endpoint to do so.
you can only CRUD-request groups. But they are not linked with any other part of the system as it seems.

Please expose or document an existing endpoint for assigning user groups to projects.

Thanks in advance

**Comment by joeriharleman** [comment]
Hello @Dakror!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
