### ISSUE TITLE
Toggl Reports API shows time on dates that I haven't recorded anything..

### ISSUE THREAD

**Issue by mihkell** [toggl/toggl_api_docs#313]
I make a request: `"https://toggl.com/reports/api/v2/weekly.pdf?workspace_id=" + WORKSPACE_ID + "&user_agent=api_test&project_ids=123916159"`

And it shows like I have time entries for the future - today+3 days all filled up.
Why is it happening like so?

**Comment by joeriharleman** [comment]
Hello @mihkell!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
