### ISSUE TITLE
301 on www.toggl.com

### ISSUE THREAD

**Issue by RickyB98** [toggl/toggl_api_docs#317]
As of this morning, an API client that I was using broke because the www.toggl.com returns 301 and redirects to toggl.com - my client was not programmed to follow redirects. I reckon this might break many clients, so probably it should be kept in as a deprecated (?) legacy URL, and probably an email should be sent to tell developers to switch.
Thanks!

**Comment by alexriziy** [comment]
Same here

**Comment by alexhermida** [comment]
Same here..

**Comment by 3nvy** [comment]
Same :/

**Comment by ricotheque** [comment]
Hey guys, sorry about that. We recently added a 301 redirect to improve our site’s SEO, and unfortunately this affected clients using our API as well. We’ve temporarily reverted the redirect as it was causing some problems with our integrations, so things should be working now.

To prevent a similar situation from happening again, can you guys please do the following?

1. Add provisions for HTTP redirects to your clients
2. Change all references to our API to https://api.toggl.com

Do let us know if there any more issues encountered!

**Comment by shedokan** [comment]
Closing as fixed
