### ISSUE TITLE
¿Feature?  Create New User

### ISSUE THREAD

**Issue by austinlg** [toggl/toggl_api_docs#318]
hello, 
I was trying to figure out if it was possible to create a new user via your api? I'm writing a client app for toggl and would like to be able to wrap the signup workflow around the app rather than direct them away if they have not signed up yet.

Thanks, 
Austin

**Comment by AuHau** [comment]
Yeah you can just POST to `/api/v8/signups` more here: https://github.com/toggl/toggl_api_docs/blob/master/chapters/users.md#sign-up-new-user
