### ISSUE TITLE
Implement filtering for all end points

### ISSUE THREAD

**Issue by sfister5** [toggl/toggl_api_docs#320]
Would like to be able to retrieve tasks and projects by name  using equality and like.

**Comment by crocokyle** [comment]
Yes, I agree. I'm struggling to come up with a solution for getting project IDs. This makes it very difficult to update tasks programmatically

**Comment by crocokyle** [comment]
Here is a generic solution I came up with for python:

`def togglProjectSearch(pname, wid):
    togglAuth = (togglApiKey, togglPassword)
    tURL = "https://api.track.toggl.com/api/v8/workspaces/", wid, "/projects"
    togglResponse = requests.get(tURL, auth=togglAuth)
    
    if togglResponse == '':
        print("No projects matching", pname, "were found by the Toggl API.")
    else:    
        pythonResponse = json.loads(togglResponse.content)
        for p in pythonResponse:
            pid = False
            if pname in p['name']:
                pid = p['id']
                print("Project match found:", p['name'], " Project ID#: ", pid)
                print("\n")
                break
        if pid == False:
            print("No projects matching ---", pname, "--- were found by pytoggl.")
        return pid
    time.sleep(1)`

**Comment by crocokyle** [comment]
Here is a generic solution I came up with for python:

```python
def togglProjectSearch(pname, wid):
    togglAuth = (togglApiKey, togglPassword)
    tURL = "https://api.track.toggl.com/api/v8/workspaces/", wid, "/projects"
    togglResponse = requests.get(tURL, auth=togglAuth)
    
    if togglResponse == '':
        print("No projects matching", pname, "were found by the Toggl API.")
    else:    
        pythonResponse = json.loads(togglResponse.content)
        for p in pythonResponse:
            pid = False
            if pname in p['name']:
                pid = p['id']
                print("Project match found:", p['name'], " Project ID#: ", pid)
                print("\n")
                break
        if pid == False:
            print("No projects matching ---", pname, "--- were found by pytoggl.")
        return pid
    time.sleep(1)```

**Comment by joeriharleman** [comment]
Hello @sfister5!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
