### ISSUE TITLE
Can't delete using API - time_entry_id is out of range for ID.

### ISSUE THREAD

**Issue by danielabbatt** [toggl/toggl_api_docs#323]
I'm getting a 400 bad request message using the API
"time_entry_id is out of range for ID. Max allowed value is 1000000000."
The id's coming back are indeed over that value, how am I supposed to delete them using the API (v8)?

DELETE to https://api.toggl.com/api/v8/time_entries/1000031075,1000031068
where there is a comma separated list and as you can see, the individual values are over the value quoted in the message.

Prior to 2018-10-08 the id's are below that value but now they are over.

Interestingly I'm pretty sure I could delete them last week as the tool runs hourly and deletes a range and replaces them with new data and it was working all last week. I guess the newly created Ids have now gone over this magic 1000000000?

**Comment by cocinerox** [comment]
Same issue here.

```
Response [https://api.toggl.com/api/v8/time_entries/1000xxxxxx]
  Date: 2018-10-15 09:46
  Status: 400
  Content-Type: text/plain; charset=utf-8
  Size: 71 B
time entry ID is out of range for ID. Max allowed value is 1000000000.
```

**Comment by shedokan** [comment]
Hey guys, thanks for reporting this.
We will be releasing a fix soon, sorry for the inconvinience.

**Comment by JayKey** [comment]
I also have the same problem when getting entry details. When I try to stop entry I get 'Invalid time_entry_id'

**Comment by vinceww** [comment]
Same problem here. It began 9 hours ago or so.

**Comment by shedokan** [comment]
Locked this issue to stop "same here" comments, once we've deployed the fix we'll close this one.
If there are other issues please create another issue or contact our support team at support@toggl.com

**Comment by shedokan** [comment]
We have deployed a fix for this issue
