### ISSUE TITLE
Bug with time entries with high id

### ISSUE THREAD

**Issue by daninr** [toggl/toggl_api_docs#325]
Hello,

I'm working with this API and I found an error that does not allow me to use anymore.

Now all time entries ID in Toggl are greather than 100 million.

It seems all IDs higher that are not possible to get time entry details.

If I do the request with an ID like: 996442425 it works perfect but if I do with ID: 1002821101 then it does not works! Returns me this error:

> Client error response
> [status code] 400
> [reason phrase] Bad Request

URL request: https://www.toggl.com/reports/api/v2/details?user_agent=USER_AGENT&workspace_id=WORKSPACE&since=2018-09-18&billable=both&time_entry_ids=1002821101&display_hours=minutes&page=1

Please can you solve it?

Thanks you,

**Comment by lovromazgon** [comment]
Hi @daninr! Thanks for pointing out the issue, seems like it's related to https://github.com/toggl/toggl_api_docs/issues/323. We're looking into it.

Sorry for the trouble!

**Comment by lovromazgon** [comment]
We just deployed a fix, this should be solved now.

**Comment by daninr** [comment]
Thanks! It's working now.
