### ISSUE TITLE
As Workspace Admin Edit Other User's Time Entries

### ISSUE THREAD

**Issue by jk464** [toggl/toggl_api_docs#326]
As per the title, is there anyway using the API to edit other users time entries in the workspace, if you are a workspace admin?

**Comment by joeriharleman** [comment]
Hello @jk464!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
