### ISSUE TITLE
Docs showing wrong response.

### ISSUE THREAD

**Issue by Detn8** [toggl/toggl_api_docs#331]
This page (https://github.com/toggl/toggl_api_docs/blob/master/chapters/authentication.md) shows a response with projects listed in the body. Projects don't show with that request.

**Comment by chrisaligent** [comment]
You're right, it's including the Related Data even though the URL doesn't include the `with_related_data=true` parameter.

I've submitted a PR to fix this:
https://github.com/toggl/toggl_api_docs/pull/336

**Comment by joeriharleman** [comment]
Hello @Detn8!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
