### ISSUE TITLE
Detail Report Error - Old api is deprecated

### ISSUE THREAD

**Issue by celliott113** [toggl/toggl_api_docs#332]
Greetings!

When attempting to utilize the call for detailed reports, I receive the error message **"Old api is deprecated"**.

According to the doc listed here: https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md

It states to utilize v2 of the API but all other docs refer to v8. I did try utilizing v8 instead but receive a 404 error.

Syntax and output below:

**Syntax:** curl -v -u <my api token here>:api_token -X GET https://www.toggl.com/api/v2/details?workspace_id=2349903&since=2019-01-01&until=2019-01-13&email=<insert user email here>

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 35.190.66.65...
* TCP_NODELAY set
* Connected to www.toggl.com (35.190.66.65) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=EE; postalCode=10117; ST=Harju; L=Tallinn; street=Tartu mnt 25; O=Toggl OU; OU=PremiumSSL Wildcard; CN=*.toggl.com
*  start date: Oct  8 00:00:00 2018 GMT
*  expire date: Jan  9 23:59:59 2021 GMT
*  subjectAltName: host "www.toggl.com" matched cert's "*.toggl.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'my api token here'
* Using Stream ID: 1 (easy handle 0x55e2fa7cf900)
> GET /api/v2/details?workspace_id=2349903 HTTP/2
> Host: www.toggl.com
> Authorization: Basic MTA2Yjc1MmIxN2I2YzlhYjllZmZhNGQ3MzdmZTg0YzI6YXBpX3Rva2Vu
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 410 
< server: nginx
< date: Mon, 14 Jan 2019 22:35:25 GMT
< content-type: application/octet-stream
< content-length: 21
< instance: web1
< strict-transport-security: max-age=15552000; includeSubDomains
< x-content-type-options: nosniff
< x-we-are-hiring: https://toggl.com/jobs/
< x-request-id: 0bda0660d687411b119b131f8a4fd50f
< via: 1.1 google
< set-cookie: GCLB=CI3NzLn9iYSdZQ; path=/; HttpOnly
< alt-svc: clear
< 
* Connection #0 to host www.toggl.com left intact
Old api is deprecated
[1]   Done                    curl -v -u <my api token here>:api_token -X GET https://www.toggl.com/api/v2/details?workspace_id=2349903
[2]-  Done                    since=2019-01-01
[3]+  Done                    until=2019-01-13

Everything appears to be working just fine when calling items from v8 API. So I am not quite sure what's causing the v2 to not work unless there's a new version not documented yet.

Any assistance would be greatly appreciated!🤘

**Comment by chrisaligent** [comment]
@celliott113 Wrong API namespace :wink: 

You're querying:
`/api/v2/details`

You want:
`/reports/api/v2/details`

Should work once you update the URL :slightly_smiling_face:

**Comment by joeriharleman** [comment]
Hello @celliott113!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
