### ISSUE TITLE
Swaager / OpenAPI API description

### ISSUE THREAD

**Issue by chatelao** [toggl/toggl_api_docs#337]
It would be great, if you could provide the API description as Swagger aka OpenAPI.

**Comment by chrisbues** [comment]
The would be wonderful. There's no Postman collection either.

**Comment by dj8** [comment]
I whole-heartedly agree!

**Comment by desrod** [comment]
I can take a stab at the Postman collection, as I've already done these for NextDNS, MAAS and other fun projects.

**Comment by joeriharleman** [comment]
Hello @chatelao!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
