### ISSUE TITLE
Provide a test endpoint that gives a warning without an error

### ISSUE THREAD

**Issue by neilmayhew** [toggl/toggl_api_docs#343]
Many HTTP client libraries throw an exception when a non-200 status code is returned. This makes it impossible to test the API client code path that detects and handles warnings using an endpoint that also generates an error. Please provide a test endpoint in addition to `error400` and `error500` that returns a warning without an error (eg `warning200` would be good). If there's already a way to do it with the existing endpoints, please document that. Thanks.

**Comment by joeriharleman** [comment]
Hello @neilmayhew!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
