### ISSUE TITLE
Webhook Support

### ISSUE THREAD

**Issue by gpattersonm** [toggl/toggl_api_docs#346]
Is it possible to get support for webhooks? I think it would be really great to have this capability so that when integrating work services like Zapier out Integromat that things could be triggered real-time instead of needing to run on a schedule.

**Comment by F-V** [comment]
#64 Same issue/request

**Comment by F-V** [comment]
Duplicate of #64

**Comment by chrisaligent** [comment]
Been asking for this since 2013. Don't hold your breath.
However a Toggl Zapier integration already exists, if that helps:
https://zapier.com/apps/toggl/integrations/webhook

**Comment by kovin** [comment]
Webhooks have been implemented :rocket: Announcement in related [issue](https://github.com/toggl/toggl_api_docs/issues/64#issuecomment-1149792924)
