### ISSUE TITLE
Improve v9 API for Time entiries

### ISSUE THREAD

**Issue by Abdulbaqi-Alshareef** [toggl/toggl_api_docs#348]
When trying to add new time entry with needed data as posting this json
``` 
 {
 	 "start": "2019-10-15T12:15:33+00:00",
 	  "description": "new time entry",
 	  "created_with":"postman"
 }
```
to API v9 URL:
https://toggl.com/api/v9/workspaces/{workspaceId}/time_entries
I got this message 
> wid is required for time entry creation

I think there is no need to specify wid because the backend already know it from URI

Also When getting time entry there is duplication of data like workspace id and user id duplicated twice 
wid=workspace_id
uid=user_id

**Comment by JOGUI22** [comment]
@Abdulbaqi-Alshareef Did you make it work? I'm having the same problem in this endpoint, but putting the 'wid' field tells me "Unexpected "wid" type string, offset=48"

**Comment by joeriharleman** [comment]
Hello @Abdulbaqi-Alshareef!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
