### ISSUE TITLE
Differences generating a PDF report using API or Toggl Web

### ISSUE THREAD

**Issue by JOGUI22** [toggl/toggl_api_docs#356]
Hello Toggl team:

I'm working in a little script to export the Monthly Summary Reports of all the users in my workspace in .pdf mode. Your API make this kind of integrations easy, and that's great!

But I found some discrepancies with the PDF generated using the API, and the PDF generated using the www.toggl.com webapp.

Aside from the style changes, I've found that in the information of the PDF generated by the API is **missing the daily hours on top of each bar in the bar chart**. I attach images of both versions to show the diff:

![image](https://user-images.githubusercontent.com/5580229/70707363-3f602280-1cd8-11ea-9606-ac184ef7409b.png)
PDF generated using API.

![image](https://user-images.githubusercontent.com/5580229/70707452-746c7500-1cd8-11ea-9a71-1a9a610132e1.png)
PDF generated using the Toggl Web.

Maybe the PDF generation code of the toggl API is older than the one used in the web. Could it be possible to update it to generate the same PDF files?

I need to generate the latest version of PDF reports (as they appear in the web mode). 

Waiting for your reply, thanks for all! :)

Bye!

**Comment by majatrepsic** [comment]
Yes, this is happening because our web is using a newer API. Unfortunately, this API is not yet fully finished and documented, but we're working hard on making it publicly available as soon as possible.

**Comment by JOGUI22** [comment]
Hello!

Just a friendly ping to know how this situation is going, and if we can expect to have this small feature this year :)

**Comment by justinffortier** [comment]
@majatrepsic Has the PDF API gone away? Whenever I add `.pdf` to my request the response is simply:

```This is not the page you are looking for!```

Here is what I am sending
```
curl --location --request GET 'https://api.track.toggl.com/reports/api/v2/summary/summary.pdf?user_agent=api_test&workspace_id=XXXX&client_ids=56041252' \
--header 'Authorization: Basic XXXX
```'

**Comment by phoenix147** [comment]
May i ask why this issue was closed?
The problem still persists!
