### ISSUE TITLE
No way to get detailed report without pagination

### ISSUE THREAD

**Issue by michelle-arzul** [toggl/toggl_api_docs#358]
I notice that there is no (documented) way to get a detailed report for a set time frame as a single response if there are more than 50 results (the only value I can get `per_page`). I would like to be able to get the same data as what can be downloaded via web interface, i.e. all the data in one object, but via the API. I've tried setting the `page` parameter to zero but this still returns only the first page (without error). Any chance this is possible with a single request?

**Comment by joeriharleman** [comment]
Hello @michelle-arzul!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
