### ISSUE TITLE
Set 'default_wid' on the '/signups' endpoint.

### ISSUE THREAD

**Issue by marcosvafilho** [toggl/toggl_api_docs#362]
We can't currently choose the default workspace when creating a new user through the `/signups` endpoint and it looks like Toggl sets random `default_wid` for every new user:

```javascript
// request body
{
  "user": {
    "email": "email@example.com",
    "password": "P@$$w0rD",
    "timezone": "America/Los_Angeles",
    "created_with": "My custom integration",
  }
}
```
```javascript
// response data
{
  "data": {
    "id": 5364025,
    "default_wid": 4132787, // random workspace set by Toggl
    "email": "email@example.com",
    (...)
  }
}
```

When trying to get details about the given workspace (`/api/v8/workspaces/4132787`) we get `null` as response.

Any way to create a new user **directly** inside my org workspace (always with the same email domain)? Current invitation flow does not fit our process very well.

**Comment by joeriharleman** [comment]
Hello @marcosvafilho!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
