### ISSUE TITLE
Api not available when website is not on localhost

### ISSUE THREAD

**Issue by blu3beri** [toggl/toggl_api_docs#365]
### Issue: 
When I am developing my Angular dashboard with the Toggl API everything is going "smoothly". But when I want to host my website I can't make any calls to the API.

I assume the problem has something to do with CORS , but CORS whitelisting has been disabled... Did anyone else encounter this issue or even better, have a solution for this?

cheers

**Comment by Berend13** [comment]
Resolved, contact toggl for CORS whitelisting.
