### ISSUE TITLE
Undocumented endpoint /project_groups

### ISSUE THREAD

**Issue by blu3beri** [toggl/toggl_api_docs#367]
The endpoint ```/project_groups``` is nowhere to be found in the documents, while it is available. I assume it would work the same as ```/project_users```.

**Comment by lubosbednar** [comment]
It is absolutely needed. I'd like to avoid assigning individual users to project.

**Comment by blu3beri** [comment]
It is available! It is just undocumented. It returns the ids of the groups the project has.

**Comment by lubosbednar** [comment]
Thanks! Both GET and POST requests work fine.

**Comment by tammomueller** [comment]
> Thanks! Both GET and POST requests work fine.

@lubosbednar 
What does the payload look like? I assume its `pid` for the project_id. But what do we use for the group id ? `gid` or `group_id` won't work for posts.
