### ISSUE TITLE
API for desktop activity data?

### ISSUE THREAD

**Issue by Etyre** [toggl/toggl_api_docs#370]
The desktop app can record user activity. I can download this data (for the past week) from the toggl website (go to "my profile" and click "export account data").

But as near as I can tell, there's no API for this. It would be really useful if there was one, so that I could set up a script to automatically export that data.

**Comment by joeriharleman** [comment]
Hello @Etyre!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
