### ISSUE TITLE
Undocumented properties on /workspace_users

### ISSUE THREAD

**Issue by COsborn2** [toggl/toggl_api_docs#371]
https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspace_users.md

This is provided as an example of a API response:
```
{
    "id":3123855,
    "uid":35224123,
    "wid":777,
    "admin":false,
    "active":false,
    "email":"John@toggl.com",
    "at":"2013-05-17T16:50:36+03:00",
    "name":"John Swift",
    "invite_url":"https://toggl.com/user/accept_invitation?code=fb3ad3db5dasd123c2b529e3a519826"
}
```
However, this is the response I am receiving.
```
{
    "id": 111111,
    "uid": 111111,
    "wid": 111111,
    "admin": false,
    "owner": false,
    "active": true,
    "email": "myemail@email.com",
    "timezone": "America/Los_Angeles",
    "inactive": false,
    "at": "<DateTimeOffset>",
    "name": "Cameron Osborn",
    "group_ids": null,
    "rate": null,
    "labour_cost": null,
    "invite_url": null,
    "invitation_code": null,
    "avatar_file_name": null
}
```

**Comment by joeriharleman** [comment]
Hello @COsborn2!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
