### ISSUE TITLE
Time entries retrieval by date range does not return other users' time entries

### ISSUE THREAD

**Issue by modgeosys** [toggl/toggl_api_docs#372]
According to [https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range), the output of `GET https://www.toggl.com/api/v8/time_entries` should include time entries for all users in a workspace where the user is an admin.  However, the output only includes my own time entries, even though I'm the admin/owner on the project and someone else's time entries exist there.

**Comment by MattiasMartens** [comment]
I'm seeing this too. Would very much like to know if it's the documentation or the behaviour that's faulty (i.e. is there some kind of security / architecture limitation here or is it just an oversight?).

I'm writing an integration to sync a team's time entries from Toggl to AirTable, so I obviously need to get everyone's entries. I can do it by getting the API key of each user, but I'd prefer to avoid that.

**Comment by MattiasMartens** [comment]
#333 appears to be related to this, although it is only intended to reword the docs without changing the actual meaning

**Comment by modgeosys** [comment]
> #333 appears to be related to this, although it is only intended to reword the docs without changing the actual meaning

Yes, it’s really a design issue brought on by the two different APIs.  I had to implement a separate API client adapter that uses the reporting API, just for the single function of retrieving time entries across my teams.

**Comment by joeriharleman** [comment]
Hello @modgeosys!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
