### ISSUE TITLE
Is there a way to get user rates?

### ISSUE THREAD

**Issue by mattostanik** [toggl/toggl_api_docs#376]
Is there a way to get the default billable rate for each user via the API?

This is the same information that appears for each user on the Team page in the Toggl web app. It does not appear to be returned in a users request via the API.

**Comment by insane4sure** [comment]
You can get that property from workspace_users (https://www.toggl.com/api/v8/workspaces/{workspace_id}/workspace_users).  It appears to be undocumented, but I just tested with success.

See https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspace_users.md

**Comment by joeriharleman** [comment]
Hello @mattostanik!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
