### ISSUE TITLE
Canonical API Client?

### ISSUE THREAD

**Issue by KevinVillela** [toggl/toggl_api_docs#379]
Hi all,

The referenced [Code Examples](https://github.com/toggl/toggl_api_docs#code-examples) are extremely helpful in figuring out how to use the Toggl API, but it still took me a couple of hours to figure out exactly how to authenticate and make the API calls I needed to (I consider myself a slightly arrogant and slightly above-average developer, but I may be below-average here). I was considering making a canonical API Client that would wrap the Toggl API and would allow a new developer to get up and running in a few minutes. It could provide features like:

- Authentication
- Clean, well-documented code and simple examples
- Consistent error handling
- Strong typing of requests and responses (in the case of Python/TypeScript/etc)

I see that this sort of thing already exists for [Elixir](https://github.com/diacode/togglex) and [Go](https://github.com/dougEfresh/gtoggl) and likely some other languages, but I was curious about the Python examples - I didn't see any simple/intuitive wrappers there like for the other languages (I may have just missed them). I would be happy to contribute something like this in Python/TypeScript/whatever language you think is the most popular, if you think it would be useful.

PS: Thanks a ton for making this API. I use Toggl to track everything, mostly through Google Assistant, which was only possible because this API exists.

**Comment by fedderw** [comment]
Seconding this. I'm not very good at this, and it's frustrating that copying and pasting the examples from 

> Hi all,
> 
> The referenced [Code Examples](https://github.com/toggl/toggl_api_docs#code-examples) are extremely helpful in figuring out how to use the Toggl API, but it still took me a couple of hours to figure out exactly how to authenticate and make the API calls I needed to (I consider myself a slightly arrogant and slightly above-average developer, but I may be below-average here). I was considering making a canonical API Client that would wrap the Toggl API and would allow a new developer to get up and running in a few minutes. It could provide features like:
> 
> * Authentication
> * Clean, well-documented code and simple examples
> * Consistent error handling
> * Strong typing of requests and responses (in the case of Python/TypeScript/etc)
> 
> I see that this sort of thing already exists for [Elixir](https://github.com/diacode/togglex) and [Go](https://github.com/dougEfresh/gtoggl) and likely some other languages, but I was curious about the Python examples - I didn't see any simple/intuitive wrappers there like for the other languages (I may have just missed them). I would be happy to contribute something like this in Python/TypeScript/whatever language you think is the most popular, if you think it would be useful.
> 
> PS: Thanks a ton for making this API. I use Toggl to track everything, mostly through Google Assistant, which was only possible because this API exists.

I'm interested as well, I'm not a developer, I just need some of this data for my personal use and I find the code examples don't work with my credentials. Do you know if anyone else has made this?

**Comment by KevinVillela** [comment]
I never got around to it, not sure if anyone else has done it either, sorry!

**Comment by joeriharleman** [comment]
Hello @KevinVillela!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
