### ISSUE TITLE
Updating a time entrie's stop time lead to inconsistent state

### ISSUE THREAD

**Issue by christophe-riolo** [toggl/toggl_api_docs#380]
Hi,
I am currently trying to write bindings to toggl v8 API an found the following bug while running my tests:

## Steps to reproduce
1. Create a finished time entry
2. Change the stop time using the `PUT /api/v8/time_entries/<tid>` endpoint
3. Change another field e.g. description

## Expected result
Duration (or start time) is modified so that `stop_time = start_time + duration`

## Actual result
- After step 2. the `stop_time` only is changed, so `stop_time != start_time + duration` which is an inconsistent state
- After step 3. the stop time is automatically recalculated so `stop_time = start_time + duration`, even though we did not ask to modify it, which is counter intuitive

**Comment by joeriharleman** [comment]
Hello @christophe-riolo!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
