### ISSUE TITLE
Is there a way to see in the api if a task is bilable?

### ISSUE THREAD

**Issue by teusch** [toggl/toggl_api_docs#381]
I'm using /api/v8/ to get Tasks but i am not able to find the property which shows whether the Task is supposed to be billable. In other words, if the task has te $ or not. see screenshot

![image](https://user-images.githubusercontent.com/5502583/88145502-c8d6bc00-cbfa-11ea-8606-7e606f5d1533.png)

**Comment by insane4sure** [comment]
The short answer to your question is that you can determine if a Task if Billable by looking at the Project for that Task.

Your screenshot shows Time Entries, which can be billable (see billable property https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md, also see is_billable property if using the Report API https://github.com/toggl/toggl_api_docs/blob/master/reports/detailed.md).  

Tasks do not have a Billable property.  However, tasks are associated to Projects.  Projects have a Billable property, which sets the default Billable value of all Time Entries created under that project (see "Billable" property https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md).  Regardless of the Project Billable property setting, the Billable property on Time Entries in that Project can be changed.

**Comment by joeriharleman** [comment]
Hello @teusch!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
