### ISSUE TITLE
Get time entry details results in 404

### ISSUE THREAD

**Issue by insane4sure** [toggl/toggl_api_docs#383]
Following the documentation here https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entry-details.

**Problem: Submitting a request for Time Entry Details for a specific entry results in a 404 response instead of a data response.**

**Problem scenario producing an unexpected/bad result (HTTP/1.1 404 Not Found)**
https://www.toggl.com/api/v8/time_entries/1664274882 

**Demonstration scenario producing an expected positive result (data)**
https://www.toggl.com/api/v8/time_entries 

**Demonstration scenario producing an expected positive result (data)**
https://www.toggl.com/api/v8/time_entries/current results in data

**Demonstration scenario producing an expected negative result (results in HTTP/1.1 400 Bad Request, strconv.ParseInt: parsing "1664280604,1664280604": invalid syntax)**
https://www.toggl.com/api/v8/time_entries/1664274882,1664274882 

_Please note that the time_entry_id 1664274882  exists and was retrieved via the toggl report api._

_I did try the new URL (https://api.track.toggl.com/api/v8/time_entries/1664310098), which produces the same results as above_

**Comment by joeriharleman** [comment]
Hello @insane4sure!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
