### ISSUE TITLE
Audit fields for time_entries

### ISSUE THREAD

**Issue by matiasalbacetti** [toggl/toggl_api_docs#387]
Hi!

It would be very useful if you could provide both the "created_at" time and "updated_at" time in the time_entries module.

Currently I use the "at" field but it seems to behave like "updated_at" and I would find it useful to know when the time entry was created.

Thanks

**Comment by joeriharleman** [comment]
Hello @matiasalbacetti!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
