### ISSUE TITLE
[Feature request] Create a read-only API token

### ISSUE THREAD

**Issue by john-sandall** [toggl/toggl_api_docs#393]
It would be great to be able to create an API token which has read-only access to my Toggl account.

Our use-case is being able to generate reports from across our entire Toggl workspace whilst not giving our DevOps team the ability to change any of our Toggl data, as this would represent an audit risk.

**Comment by joeriharleman** [comment]
Hello @john-sandall!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
