### ISSUE TITLE
time_entry_id is out of range for ID. Max allowed value is 1800000000.

### ISSUE THREAD

**Issue by twpol** [toggl/toggl_api_docs#396]
I am receiving the following error when attempting to use the [Toggl API](https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md) in [my client](https://github.com/twpol/toggl-cli):

```time_entry_id is out of range for ID. Max allowed value is 1800000000.```

It looks like this is from the API server, and is validation that's no longer correct. Developer Tools on the website reveal my last couple of timer entries are above the 1800000000 value:

![image](https://user-images.githubusercontent.com/1017843/101374236-d341db80-38a5-11eb-8df7-89419a7993d5.png)

Any chance we could get this fixed ASAP? I would guess that all third-party clients which attempt to write to Toggl will be affected.

Thanks!

**Comment by gilberthdez** [comment]
hi @twpol , thanks for reaching out... fix it's already rolled!

**Comment by twpol** [comment]
Beautiful, thanks!
