### ISSUE TITLE
400 returned if query contains 1800007885

### ISSUE THREAD

**Issue by BorisSK** [toggl/toggl_api_docs#397]
Hi,

I think I've hit a bug in you web interface:

* trying to access following URL
`https://track.toggl.com/reports/detailed/3651744/period/yesterday/timeEntryIds/1799600505,1799781560,1800007885`

* which returns `400`:

`{"error":{"message":"time_entry_ids=1799600505,1799781560,1800007885 is too big","tip":"Change your request and try again. Please refer to API documentation at https://github.com/toggl/toggl_api_docs if you need additional help","code":400}}`

* problem goes away if 1800007885 is removed from the query
* concerned record is visible in summary tab without any issues

Thanks! :)

b.

**Comment by joeriharleman** [comment]
Hello @BorisSK!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
