### ISSUE TITLE
Increase Rate Limit

### ISSUE THREAD

**Issue by kluhman** [toggl/toggl_api_docs#398]
Because of the lack of webhooks, we are forced to poll for new and updated timesheet entries whenever we want to update our other reporting services. When paging over results from the detailed report page, 1 request per second is just not enough with only 50 results per page

**Comment by kovin** [comment]
Webhooks have been implemented :rocket: Announcement in related [issue](https://github.com/toggl/toggl_api_docs/issues/64#issuecomment-1149792924)
