### ISSUE TITLE
Increase or Allow Override of Per Page Value

### ISSUE THREAD

**Issue by kluhman** [toggl/toggl_api_docs#399]
We're building a tool that integrates with Toggl and we end up pulling timesheet data out to report on. We use the detail report API so we can customize time frames and other properties we filter by, but 50 results per page is such a small page size for large projects. It would be very useful to either increase the number of results per page or to allow the caller to up the limit, especially considering a pretty restrictive rate limit

**Comment by Jonkat323** [comment]
Did you ever figure out a solution to this?

**Comment by kluhman** [comment]
@Jonkat323 Nope, we've just had to deal with the existing limit

**Comment by joeriharleman** [comment]
Hello @kluhman!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
