### ISSUE TITLE
Change project color to HEX

### ISSUE THREAD

**Issue by DorZuberi** [toggl/toggl_api_docs#401]
Hello,
It would be awesome if we could create or update a project and pass a hex code for color instead of color code.

There is also no documentation for the color codes and their values.

**Comment by joeriharleman** [comment]
Hello @DorZuberi!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
