### ISSUE TITLE
[Reference] Add Tableau Web Data Connector API? 

### ISSUE THREAD

**Issue by mhwangbo11** [toggl/toggl_api_docs#402]
Hello, I was trying to browse easier way for our C-suite managers to link Toggl to data viz software (i.e. MS Power BI, Tableau...)
and found this working repo from Keshia Rose. 

Can we add this as one of the Third Party App reference?

- Author: Keshia Rose @ KeshiaRose
- Contributor: Nick Maher @ nickmaher84
- Link: https://github.com/KeshiaRose/Toggl-Web-Data-Connector
- Description: This Tableau Web Data Connector pulls in your task tracking data from the Detail Reports view on toggl.com

**Comment by joeriharleman** [comment]
Hello @mhwangbo11!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
