### ISSUE TITLE
Cannot Create Project with ClientId ("cid")

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [toggl/toggl_api_docs#404]
If I try to create or update a project with 'cid', the request succeeds, but there is no 'cid' in the returned json from that project.
Is this broken or is there something I'm missing?

**Comment by Anti-Distinctlyminty** [comment]
This is what I'm trying 

```python
data={'project': {'cid': 215}}
r = requests.put(f'https://api.track.toggl.com/api/v8/projects/1234567',
				json=data,
				auth=requests.auth.HTTPBasicAuth(apiToken, 'api_token'))
```

The response is 200 OK, yet I see no `cid` in the returned data.

**Comment by joeriharleman** [comment]
Hello @Anti-Distinctlyminty!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
