### ISSUE TITLE
Toggl Track Login failed_Are you online?

### ISSUE THREAD

**Issue by VictorLECHOVOLEA** [toggl/toggl_api_docs#405]
Hello Toggl Track team,
I have issues logging in from a desktop device.
I reinstalled today the app but nothing changed.

Thank you in advance for taking this issue into account!
Best Regards, 
Victor

Check the image.
![Toggl Track_failed login_Are you online](https://user-images.githubusercontent.com/50649861/111262786-7df83180-862d-11eb-94fb-17f0ce8fde58.jpg)

**Comment by joeriharleman** [comment]
Hello @VictorLECHOVOLEA!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
