### ISSUE TITLE
Duration doesn't match start and stop time in the example for Time Entries

### ISSUE THREAD

**Issue by bytrangle** [toggl/toggl_api_docs#406]
In the [chapters/time_entries.md](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md) file, under the *Updatie a time entry* section, the example for a successful response seemed inaccurate.

```
{
	"data":
	{
		"id":436694100,
		"pid":123,
		"wid":777,
		"billable":false,
		"start":"2013-03-05T07:58:58.000Z",
		"stop":"2013-03-05T08:58:58.000Z",
		"duration":1240,
		"description":"Meeting with possible clients",
		"billable": true,
		"at": "2013-03-05T12:34:50+00:00"
	}
}
``` 
You can see immediately that the stop time is exactly one hour after the start time, which means the duration should be 60 minutes or 3600 seconds. But the `duration` field in the response is 1240.

The `1240` value is what was provided in the request to update the time entry, but doesn't Toggl API have a mechanism to check the duration?

**Comment by joeriharleman** [comment]
Hello @bytrangle!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
