### ISSUE TITLE
ISO8601 time format doesn't look right

### ISSUE THREAD

**Issue by shindosu** [toggl/toggl_api_docs#409]
Hi,
I'm not sure if this is the right place to ask, but I am trying to make a request to get time entries between a start and end date. I noticed that the time format for `start_date` and `end_date` is not in the iso 8601 format that I know. I thought iso 8601 was something like `2021-05-20T00:19:57+00:00`, but in the docs a valid parameter is in the format `2021-05-20T00%3A00%3A00%2B02%3A00`. 

What is this 3A and 2B?

**Comment by pgonera** [comment]
2021-05-20T00%3A00%3A00%2B02%3A00` is `2021-05-20T00:00:00+02:00` in url encoded form. Have look at https://www.urldecoder.org/ there is an explanation how encoding and decoding is done. You should have tools for it in your programming environment.

**Comment by shindosu** [comment]
> `2021-05-20T00%3A00%3A00%2B02%3A00` is `2021-05-20T00:00:00+02:00` in url encoded form. Have look at https://www.urldecoder.org/ there is an explanation how encoding and decoding is done. You should have tools for it in your programming environment.

Thank you very much for the explanation! Just what I needed.
