### ISSUE TITLE
API Clients, Open API, Generating, documentation?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [toggl/toggl_api_docs#411]
Hi Toggl, do you have a definition of your API as an Open API yml file?
https://swagger.io/specification/

Stoplight Studio could be used to make one, it's a little bit buggy but useable.
https://stoplight.io/studio/

Another quick editor/previewer.
https://editor.swagger.io/

Open API Generator could be used to generate clients for the API in various things.
https://github.com/OpenAPITools/openapi-generator

See for generators there are many e.g. Clients, documentation generators etc.
https://openapi-generator.tech/docs/generators
You could generate a md or html which could be put in the git wiki pages of this repo?

Reason I am asking this is that this repo for a node-toggl-api client is read only now and has not applied the URL changes. Maybe this is MIA/no longer maintained?
Maybe worth noting this in your README.md?
https://github.com/7eggs/node-toggl-api

Otherwise quick workaround if API has not changed other than the URL (which seems to be mostly the case?) can fork that repo or use patch-package https://www.npmjs.com/package/patch-package to tweak the URL.

Kind regards,
Liam

**Comment by joeriharleman** [comment]
Hello @LiamKarlMitchell!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
