### ISSUE TITLE
Can't Change Task Name

### ISSUE THREAD

**Issue by ChriGibs** [toggl/toggl_api_docs#414]
Whenever I use the API and specify the task ID and attempt to change the Task name - it creates a 2nd one.

![image](https://user-images.githubusercontent.com/11138269/127411945-076865d5-b8d2-43ca-9bc8-7af9b3ec0ef9.png)

**Comment by joeriharleman** [comment]
Hello @ChriGibs!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
