### ISSUE TITLE
How to get group members?

### ISSUE THREAD

**Issue by ReinsBrain** [toggl/toggl_api_docs#420]
I can get workspace groups, but i can't find way to list members of a group. What am I missing?

**Comment by TobiasKeitsch** [comment]
I can't find any documentation regarding group membership either.

The only thing I can find is that the Web UI (`https://track.toggl.com/organization/<id>/groups`) is using the API: `https://track.toggl.com/api/v9/organizations/<id>/groups` where it responds with a users array of the group members.

**Comment by TobiasKeitsch** [comment]
I found out that the v9 API is allowing you to reuse the session you create for v8, so you can use the v9 API to get all your groups and together with their members.

`GET https://track.toggl.com/api/v9/organizations/{organization_id}/groups`


Example response:
```
[
    {
        "group_id": 123456,
        "name": "Toggl-API-Test",
        "at": "2021-12-01T00:00:00.000000Z",
        "workspaces": [
            1234567
        ],
        "users": [
            {
                "user_id": 1234567,
                "name": "Tobias",
                "avatar_url": "",
                "joined": true
            }
        ]
    }
]
```

**Comment by joeriharleman** [comment]
Hello @ReinsBrain!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
