### ISSUE TITLE
API v3 documentation on workspace time_entries totals

### ISSUE THREAD

**Issue by galloramiro** [toggl/toggl_api_docs#421]
In know that you advice about the change...   
We update most of the things but there was a hardcoded endpoint:
`https://toggl.com/reports/api/v3/workspace/{workspace_id}/search/time_entries/totals`
Now we dont know the info that this endpoint returned and I cant find something similar on the current app. 
Someone have documentation about this endpoint or a example of the data retived? 

This are the params i send to the endpoint
```
data = {
    'user_agent': self.user_agent,
    'workspace_id': workspace_id,
    'start_date': start_date,
    'end_date': end_date,
    'grouping': grouping,
    'sub_grouping': sub_grouping,
    'with_graph': True
}
```
Thanxs a lot!

**Comment by naranjamecanica** [comment]
Did you find any solution?
