### ISSUE TITLE
Is there a way to access Desktop app Activity tracking?

### ISSUE THREAD

**Issue by GitMurf** [toggl/toggl_api_docs#427]
Is there a way to access Desktop app Activity tracking which shows the active application window open in 15 minute increments? If it isn't accessible via the API, is there any way to export this data? For example I'd like to export all my tracked desktop activity for a given day.

Thanks!

**Comment by joeriharleman** [comment]
Hello @GitMurf!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
