### ISSUE TITLE
.NET reference is no longer available

### ISSUE THREAD

**Issue by kenrachynski** [toggl/toggl_api_docs#429]
I was trying to refresh an old idea I had that leaned on the C# libraries in your mobile apps as mentioned in the following

> The Toggl mobile apps have [shared C# libraries](https://github.com/toggl/mobileapp) which provide access to the API and also common clientside business logic we use. Feel free to use as little or much of it as you want.

Sadly, the linked repo appears to be gone. Where should we look now for C# libraries to access your API?

**Comment by kenrachynski** [comment]
Or maybe you can point to the various NuGet packages that are being updated in your library's stead?

We've got Toggl.Api, TogglApi.Client, TogglAPI.Net, and TogglAPI.NetStandard

**Comment by kenrachynski** [comment]
Judging from the traffic on this issue. Developers are no longer of interest to Toggl.

**Comment by joeriharleman** [comment]
Hello @kenrachynski!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
