### ISSUE TITLE
Filter Tasks by Active

### ISSUE THREAD

**Issue by Rich-PF** [toggl/toggl_api_docs#430]
With the **Summary** and **Detail** reports I'd like to be able to filter out tasks based on their `active` state (aka "Mark as done").

Alternatively, in the **Summary** report when grouping by Task it should include the details of the task including the `active` state.  Then at least I can parse out irrelevant data within my own app.

Could you please consider implementing this?

**Comment by joeriharleman** [comment]
Hello @Rich-PF!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
