### ISSUE TITLE
Non-matching pid results for provided project_id

### ISSUE THREAD

**Issue by garrettApproachableGeek** [toggl/toggl_api_docs#435]
Calling `https://api.track.toggl.com/reports/api/v2/details?user_agent={email}&workspace_id={workspace}&project_id={projectId}&page=1`

Actual:
Some returned results have a different `pid` than the provided projectId along with results that match the projectId

Expected:
Only results that match the `pid` and projectId are returned

I am tempted to use the api that the web client uses, but it sounds like API access for that will be removed, unless the note in the readme is incorrect.

**Comment by joeriharleman** [comment]
Hi Garrett,

Thank you for dropping an issue here. In case you still need support with your issue, I urge you to contact our excellent 24/5 support team through [our support pages](https://support.toggl.com/en/) (click the icon on the bottom right corner to chat with them). This repository is largely unmaintained and therefor issues are not seen by our team. I apologise for the inconvenience, we've added a note recently to prevent this in the future.

Regards,
Joeri
