### ISSUE TITLE
POST/PUT response 400 - No writer connection available. DB might be down.

### ISSUE THREAD

**Issue by sourdenis** [toggl/toggl_api_docs#436]
Hello!

I have a solution where we send client and project data to Toggl via Toggl API. 
It has worked pretty well for some time (2 years?) but today (17.05.2022) I came across this kind of error when adding or updating a project:
400 "No writer connection available. DB might be down."

It seems to been related to one account, today around 12:30-12:40 (GMT).

Is this a glitch in Toggl API or?

BR
Denis

**Comment by joeriharleman** [comment]
Hi Denis!

Thank you for dropping an issue on our Github repo. Unfortunately this repository is unwatched and issues like this go unseen. If you still need help for this issue, you can contact our 24/5 support team, they guaranteed will give you a better service. Please visit [this page](https://support.toggl.com/en/) and look for the chat icon on the bottom right corner.

Regards,
Joeri
