### ISSUE TITLE
Suggested improvements to Webhooks API documentation

### ISSUE THREAD

**Issue by michelle-arzul** [toggl/toggl_api_docs#438]
- Combining Python-style `{<variable>}` string substitution in JSON data easily lends itself to confusion, especially with cURL examples where it does not really make sense. Consider using some other notation such as Bash-style `$<variable>` or JavaScript-style `${<variable>}` instead.
- [Create a subscription](https://github.com/toggl/toggl_api_docs/blob/master/webhooks.md#create-a-subscription) does not explicitly state that the POST method must be used. By default cURL will use POST even without specifying `-X POST` when the request contains data, but in other environments this could lead to confusion if GET is used instead, which results in a 400 response.
- [Update a subscription](https://github.com/toggl/toggl_api_docs/blob/master/webhooks.md#update-a-subscription) example's data contains malformed JSON. There is a comma missing between `event_filters` and `enabled`.
- [Validating received events](https://github.com/toggl/toggl_api_docs/blob/master/webhooks.md#validating-received-events) is unclear. Consider providing a simple code example such as those below.
```py
#!/usr/bin/env python3

import hmac

def validate_received_event(signature, secret, body):
    digest = hmac.new(secret.encode('utf-8'), body.encode('utf-8'), 'sha256').hexdigest()
    return hmac.compare_digest(signature, f'sha256={digest}')
```
```rb
#!/usr/bin/env ruby

require 'openssl'

def validate_received_event(signature, secret, body)
  signature == "sha256=#{OpenSSL::HMAC.hexdigest('SHA256', secret, body)}"
end
```

Also it would be nice if the issues related to implementing webhooks were closed, since they are among the top results on a web search and the excerpts mislead one to believe that it has not yet been released.

**Comment by joeriharleman** [comment]
Hi Michelle,

Thank you for creating this issue on the repository. Unfortunately though, this repository is largely unmaintained and unwatched by our developers. On a positive note for you I can see that one of our developers has caught eye of it and mentioned it, but this process is not guaranteed to be followed up.

To keep track of the issue (pun intended? 🥲 ) and ensure follow-up, please submit your questions to our 24/5 dedicated support team [here](https://support.toggl.com/en/) -> you can chat with them fairly directly using the chat icon in the bottom right corner. I promise you that you will have a better experience with our support team :)

Regards,
Joeri
