### ISSUE TITLE
API retrieve task and project by id

### ISSUE THREAD

**Issue by powtac** [toggl/toggl_api_docs#6]
Is there a way to retrieve a single task or project by id through the public API? As far as I can see, I can only get a list of all projects (https://www.toggl.com/public/api#get_projects) and tasks (https://www.toggl.com/public/api#get_tasks).

/api/v6/projects/123
/api/v7/projects/123
/api/v8/projects/123

do not work!

Original issue: http://support.toggl.com/customer/portal/questions/781227--api-retrieve-task-and-project-by-id

**Comment by jyviko** [comment]
Hi janika,
I am trying to list all tasks under a project using:  /api/v8/projects/123/tasks but is returning null%. 
Is there another way to do this?

**Comment by janika** [comment]
hey, @jyviko! I'm not working on this anymore. Maybe @refiito can help you.

**Comment by Xstoudi** [comment]
Same problem here
https://token:api_token@www.toggl.com/api/v8/projects/2265770
Returns `null`

**Comment by dbalogh78** [comment]
Hi, I may be pretty late to the party :)
It seems tasks are maintained on Workspace scope in toggl
So you can get them 
.../workspaces/{workspace_id}/tasks
the result can be now filtered for 'pid', the project id

HTH,
Daniel
