### ISSUE TITLE
Is there a rate limit?

### ISSUE THREAD

**Issue by webbj74** [toggl/toggl_api_docs#78]
I'm wondering if there are rate limits in place, and if so, how to check where my API key is relative to it.

Example of how Github API handles this:
HTTP headers - http://developer.github.com/v3/#rate-limiting
Free API call - http://developer.github.com/v3/rate_limit/

**Comment by MaximRouiller** [comment]
Is this answer still valid?

**Comment by refiito** [comment]
No, https://github.com/toggl/toggl_api_docs#the-api-format

**Comment by lukewlms** [comment]
Here's the rate limiting info (also at the link @refiito posted):

> For rate limiting we have implemented a Leaky bucket. When a limit has been hit the request will get a HTTP 429 response and it's the task of the client to sleep/wait until bucket is empty. Limits will and can change during time, but a safe window will be 1 request per second. Limiting is applied per api token per IP, meaning two users from the same IP will get their rate allocated separately.
